### ISSUE TITLE
basic-link KButton icons are not colored properly

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri-design-system#103]
This does not account for the fact that icons associated with a `basic-link` appearance ought to show as `$themeTokens.primary`.

Additionally, it seems that icons cause the underline of the associated text to extend out a character in either direction. 

![screenshot-localhost_8080-2020 09 09-16_07_35](https://user-images.githubusercontent.com/6356129/92663614-98380800-f2b6-11ea-8a85-1d8c33a031dc.png)

**Comment by sairina** [comment]
When I used a `KButton` with a `basic-link` appearance and added icons before and after, I couldn't seem to replicate the space between the icons. However, I'll work on getting the icons to be: `$themeTokens.primary`

![Screen Shot 2021-02-11 at 2 57 48 PM](https://user-images.githubusercontent.com/13563002/107709224-b8129400-6c79-11eb-9d93-d87f9e4b7819.png)
