### ISSUE TITLE
ePub and PDF document node icons are the same

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/kolibri-design-system#113]
### Observed behavior

<img width="559" alt="kolibri iconography -- epub and pdf content nodes look the same" src="https://user-images.githubusercontent.com/163966/49626301-3b077800-f9a7-11e8-9d03-7c012b6f853a.png">

A PDF and an ePub with the same title are indistinguishable: http://35.196.115.213/learn/#/topics/t/2c953cb70c4d57dbb91a879ab4953834

### Expected behavior
<img width="559" alt="kolibri iconography -- epub and pdf content nodes look the same" src="https://user-images.githubusercontent.com/163966/49626430-d7ca1580-f9a7-11e8-9d1a-361e045584b6.png">

### User-facing consequences

Certain sources offer both a PDF and ePub version of documents with the same title. Ideally we would want to import both file formats, but it can be confusing if icons for both document sub-kinds are the same.

Severity: minor

**Comment by indirectlylit** [comment]
related: https://github.com/learningequality/kolibri-design-system/issues/102

**Comment by khangmach** [comment]
Addressed with new 0.15 learner-facing updates
