### ISSUE TITLE
cherry pick latest changes from kolibri repo

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-design-system#12]
The following changes to shared Kolibri Components have been made recently in Kolibri `develop`. They need to be added here _before_ https://github.com/learningequality/kolibri/pull/6595 is merged in

* https://github.com/learningequality/kolibri/commit/a024934233efc5538a951b6aba79d429c850b5ee#diff-7d9c37dc9a600932d07e64be8ff7b11e
* https://github.com/learningequality/kolibri/commit/c037b6e73f2f93e1a8ba741242935f1b9fa049eb#diff-053a10dd1d40a8a0dabc76d4f84cb32a
* https://github.com/learningequality/kolibri/commit/af2c8fc252ecc05fe7af2e29b1321e6d1773d8bc#diff-053a10dd1d40a8a0dabc76d4f84cb32a
* https://github.com/learningequality/kolibri/pull/6701/commits/e0b154ec901a8945eaa52dbfb5aa2ed5bddbd799
* https://github.com/learningequality/kolibri/pull/6660/files#diff-2425a6167bea4c6f2460022a0cb7a512
* https://github.com/learningequality/kolibri/pull/6830

**Comment by indirectlylit** [comment]
One thing to watch out for from https://github.com/learningequality/kolibri/commit/e0b154ec901a8945eaa52dbfb5aa2ed5bddbd799

The theming currently doesn't work for icons in links - these should be the same color:

![image](https://user-images.githubusercontent.com/2367265/78411982-a1fe6680-75c6-11ea-8014-b824be2dfad5.png)

(cc @nucleogenesis)

**Comment by nucleogenesis** [comment]
@indirectlylit do you recall if any of the merges referencing this issue close it?

**Comment by indirectlylit** [comment]
no, I don't believe so. I can take a look at this tomorrow
