### ISSUE TITLE
KTextbox needs box styling instead of underline

### ISSUE THREAD

**Issue by jayoshih** [learningequality/kolibri-design-system#124]
According to the [documentation](https://docs.google.com/document/d/1w6v-CGAM72hg5QncT913koxZQLO-n8e7_PCibBc6d-c/edit#), text fields should use box styling. This also applies to selects and text areas

![image](https://user-images.githubusercontent.com/7447496/96493134-73aa4680-11f9-11eb-809a-56217b0ebe52.png)

**Comment by indirectlylit** [comment]
more info here: https://github.com/learningequality/kolibri/issues/6033 (upgrade text boxes to new Material style)
