### ISSUE TITLE
KIconButtons don't resize well with panels

### ISSUE THREAD

**Issue by jayoshih** [learningequality/kolibri-design-system#125]
When there is limited space available, the icon button ends up looking squished. For instance, if you go to [develop Studio](https://develop.studio.learningequality.org/), open a channel with topics, and resize the navigation panel, you'll see this for the options menu

![image](https://user-images.githubusercontent.com/7447496/96493757-3befce80-11fa-11eb-8fa7-be5fff41e0e2.png)

**Comment by nucleogenesis** [comment]
@jayoshih 

I recall seeing this before - but I no longer see it on Studio's develop. If you can replicate please let me know how/where. I think that this was probably worked-around in Studio in that case and will try to find the PR where the change was made to see if we can improve the component in KDS to avoid these issues altogether.

**Comment by nucleogenesis** [comment]
@marcellamaki fixed this in https://github.com/learningequality/kolibri-design-system/pull/145
