### ISSUE TITLE
In IE11, KRadioButtons don't seem to emit any events if `currentValue` is falsy

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri-design-system#128]
In https://github.com/learningequality/kolibri/issues/7595, radio buttons are un-selectable when the `currentValue` prop is an empty string (and I think this is generally true for any falsy values). So the only fix I could think of was to initialize it with some non-empty string that was unlikely to collide with a legitimate `value` for the radio buttons.

The issue came up in this specific issue (and it might be in other places) because normally when we render a list of checkboxes, we immediately select one of the options. The form at issue intentionally does not select an option to avoid showing the username/password form underneath it when the radio button is activated.

So, we need to keep this issue in mind if we do similar controls in Studio or Kolibri. But ideally, radio buttons would "just work" even if the `currentValue` prop is falsy.

**Comment by nucleogenesis** [comment]
No need to support IE11 anymore
