### ISSUE TITLE
Studio icons missing in KDS for the substitutions in docs

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri-design-system#141]
I was not able to find [docs-substitutions](https://kolibri-design-system.netlify.app/icons/#rst) for these Studio icons:

Icon | (proposed) Name | Location
------- | ------- | -
![copy-channel-token](https://user-images.githubusercontent.com/1457929/101545840-269c5280-39a8-11eb-945f-37f19942b6a9.png)  | `copyBorder` | ![copy-channel-token-location](https://user-images.githubusercontent.com/1457929/101546214-c4901d00-39a8-11eb-8c72-b694b3f0ba09.png)
![kolibri-violet-info](https://user-images.githubusercontent.com/1457929/101546010-68c59400-39a8-11eb-9b6b-e749479454a4.png) | _possibly just missing the **colored** style_ | ![kolibri-violet-info-location](https://user-images.githubusercontent.com/1457929/101546293-dc67a100-39a8-11eb-8ee5-a1975274af8f.png)
![home](https://user-images.githubusercontent.com/1457929/101546471-1cc71f00-39a9-11eb-93a5-0b5dc7c223f0.png) | `home` | ![home-location](https://user-images.githubusercontent.com/1457929/101546829-a70f8300-39a9-11eb-925e-9f9df02bb8fc.png)
![unpublishedResource](https://user-images.githubusercontent.com/1457929/101547606-c955d080-39aa-11eb-8d98-d4bad5ec2032.png) | `unpublishedResource` | ![unpublished-location](https://user-images.githubusercontent.com/1457929/101547667-e094be00-39aa-11eb-8cc0-d2f2c04c32b6.png)
![unpublishedChanges](https://user-images.githubusercontent.com/1457929/101547726-fa360580-39aa-11eb-8078-cfc674430074.png) | `unpublishedChange` | :arrow_up: 

cc @nucleogenesis @indirectlylit

**Comment by nucleogenesis** [comment]
@radinamatic @indirectlylit did https://github.com/learningequality/kolibri-design-system/pull/104 fix this issue or are they separate issues?

**Comment by radinamatic** [comment]
As far as I understand, none of the icons that I listed above are included in the [KDS](https://kolibri-design-system.netlify.app/icons/#icons) yet, correct?

If that is so, then a new PR is needed to include/upload them, and even I can take care of updating the `rstIconReplacements.txt` file afterwards, so they can be used in the docs.

**Comment by indirectlylit** [comment]
If they're missing from [KDS aliases](https://design-system.learningequality.org/icons/#icons), they're also going to be missing from `rstIconReplacements.txt` so that's the first step. It also implies that Studio is not using KDS icons out-of-the box for these cases.

**Comment by radinamatic** [comment]
Fair enough, the _proper_ way of adding these icons would be to add both aliases and RST replacements at the same time... What I wanted to say is that _**even I**_ could easily accomplish the latter, while the former would potentially take me longer 😉 😊

**Comment by nucleogenesis** [comment]
Thank you @radinamatic and @indirectlylit for clarifying. 

Just want to leave a few thoughts for whoever follows up here.

### copyBorder aka content_copy aka `copy`

Defined here: https://kolibri-design-system.netlify.app/icons/ as `copy` - this isn't the exact same icon as you listed in December, @radinamatic,  but it is the icon used in Studio right now.

### (purple) info

I think this is used as a warning or tooltip indicator in Studio? Thoughts here @jtamiace for a useful name?

Likely solution to copy [the info icon as it is](https://github.com/learningequality/kolibri-design-system/blob/78c765dc33fb553a9cc3b693635c3a7108fc6218/lib/KIcon/iconDefinitions.js#L145) and add a `defaultColor: themeTokens().primary` property to it.

---

The published/unpublished might be a little bit tricky if we have to use an icon as our icons are designed to use up more space than those little dot icons.

**Comment by jtamiace** [comment]
@nucleogenesis to clarify, are you asking for a new alias for the purple version of `info`? If so, would `tooltip` make sense for devs? Across KDP, studio, and the learning platform, this is the only icon is used to trigger them. Otherwise, using `info` again seems fine too

**Comment by radinamatic** [comment]
@nucleogenesis 
> (`copyBorder`) isn't the exact same icon as you listed in December, but it is the icon used in Studio right now.

Both are used in Studio (current `hotfixes` branch), one in the channel cards and channel details page for copying the token to user device's clipboard, the other in channel editor for making a copy of a selected topic or resource.


Icon | (proposed) Name | Location
------- | ------- | -
![copy-channel-token](https://user-images.githubusercontent.com/1457929/101545840-269c5280-39a8-11eb-945f-37f19942b6a9.png)  | `copyBorder` | ![copy-channel-token-location](https://user-images.githubusercontent.com/1457929/101546214-c4901d00-39a8-11eb-8c72-b694b3f0ba09.png)
![Selection_004](https://user-images.githubusercontent.com/1457929/109964129-8e371500-7ced-11eb-9b06-0622fa9ff43f.png) | `copy` | ![Selection_003](https://user-images.githubusercontent.com/1457929/109964201-a4dd6c00-7ced-11eb-99a0-8dcb677ad306.png)

I proposed the `copyBorder` name since there were already a `star` and `starBorder` defined icons with same difference (one full, the other just outlined).

For the purple info icon, maybe `details` alias could work? It is used on the channel cards to open the channel details page, and the tooltips kind of give more _detailed_ information.

**Comment by indirectlylit** [comment]
> Both are used in Studio 

another option is to just choose one

**Comment by jtamiace** [comment]
@radinamatic thanks, I think `details` is much better

**Comment by radinamatic** [comment]
> just choose one

💯 

I'd vote for the _border_ version (which is **not** currently documented), looks a bit clearer to me.

**Comment by indirectlylit** [comment]
I do see that there are at least three concepts:

* copy to OS clipboard ![image](https://user-images.githubusercontent.com/2367265/110010425-22e04980-7cd3-11eb-9d64-289b3b714c83.png)
* duplicate object ![image](https://user-images.githubusercontent.com/2367265/110010386-1956e180-7cd3-11eb-885e-a8bd65c78190.png)
* show studio clipboard UI? ![image](https://user-images.githubusercontent.com/2367265/110010361-13f99700-7cd3-11eb-9f3d-98a32326c226.png)

so if the differentiation is intentional and consistent, that seems like a good thing
