### ISSUE TITLE
KDropdownMenu issues

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-design-system#164]
The `KDropdownMenu` component implements full buttons with menus like these:

![image](https://user-images.githubusercontent.com/2367265/108136537-16bb8180-706f-11eb-9938-57b058160fc0.png)

A couple issues:

* The name implies that it would just implement a menu, but it actually implements buttons that happen to have a menu
* It doesn't play nicely with `KButtonGroup`, which doesn't add internal spacing as expected

Recommend deprecating this component entirely, and adding an `options` property to `KButton` and removing `hasDropdown`.

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri-design-system/pull/346
