### ISSUE TITLE
button, router link, external link consistency and styling

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-design-system#166]
## Expected behavior

`KButton`, `KRouterLink`, and `KExternalLink` are styled exactly the same with 8px spacing between the icons and the text as here: https://github.com/learningequality/kolibri-design-system/issues/135#issuecomment-777086143

## Actual behavior

After merging in these PRs:
* https://github.com/learningequality/kolibri-design-system/pull/143
* https://github.com/learningequality/kolibri-design-system/pull/150
* https://github.com/learningequality/kolibri-design-system/pull/161

I see:

![image](https://user-images.githubusercontent.com/2367265/108570248-42827580-72c2-11eb-84b1-a5b6699c921a.png)

for:

```vue
<KExternalLink
  text="external (google)"
  href="https://google.com"
  icon="facility"
  iconAfter="facility"
/>
<br>
<KRouterLink
  text="router link (empty)"
  :to="{}"
  icon="facility"
  iconAfter="facility"
/>
<br>
<KButton
  text="button (alert)"
  appearance="basic-link"
  icon="facility"
  iconAfter="facility"
  @click="console.log('hello')"
/>
```

Additionally there are some discrepancies with the slots:

* `KButton` has `icon`, `default`, and `iconAfter` which seems correct
* `KExternalLink` is missing `default` and includes a slot called `openInNewTab` whose purpose is unclear
* `KRouterLink` has no slots at all

## Steps to reproduce the issue

Paste the code above into a test page

## Environment
- OS: MacOS
- Browser version: Chromium and Firefox

**Comment by indirectlylit** [comment]
Another thing to watch out for is that the icon(s) and text should both fade to the hover color:

| no icon hover | icon hover with CSS transition |
|--|--|
| ![2021-02-19 16 59 37](https://user-images.githubusercontent.com/2367265/108576947-3c959000-72d4-11eb-995d-def8a3a11378.gif) |![2021-02-19 17 00 15](https://user-images.githubusercontent.com/2367265/108576955-45866180-72d4-11eb-8e6a-ce9eb9db1106.gif) |

**Comment by sairina** [comment]
Thanks for the information! Questions:

1. `KExternalLink`:`openInNewTab` is from this issue, [KExternalLink ought to open in new tab safely](https://github.com/learningequality/kolibri-design-system/issues/94). From my understanding, providing `true` to this prop allows that link to open in another tab, instead of in the current tab. How might we adjust this to make sure it's more clear?
2. `KButton`: What is the purpose of `default`? It is this one, correct? 
> https://github.com/learningequality/kolibri-design-system/blob/v0.2.x/lib/buttons-and-links/KButton.vue#L23

**Comment by indirectlylit** [comment]
> 1. `KExternalLink`:`openInNewTab` is from this issue, [KExternalLink ought to open in new tab safely](https://github.com/learningequality/kolibri-design-system/issues/94). From my understanding, providing `true` to this prop allows that link to open in another tab, instead of in the current tab. How might we adjust this to make sure it's more clear?

Yes the purpose of the prop named `openInNewTab` is totally clear:

https://github.com/learningequality/kolibri-design-system/blob/4a2ae39872817e189c35db1de975c9c49b5b03fa/lib/buttons-and-links/KExternalLink.vue#L70-L76

I'm referring to the _slot_ named `openInNewTab` which was probably added by mistake:

https://github.com/learningequality/kolibri-design-system/blob/4a2ae39872817e189c35db1de975c9c49b5b03fa/lib/buttons-and-links/KExternalLink.vue#L32-L39


> 2. `KButton`: What is the purpose of `default`? It is this one, correct? 

The `default` slot allows you to pass arbitrary sub-components into the button, which provides more flexibility than and takes precedence over the `text` prop

**Comment by indirectlylit** [comment]
@sairina FYI I found the source of some of the frustrating underline issues we've had:

https://github.com/learningequality/kolibri/issues/8907
