### ISSUE TITLE
upgrade text boxes to new Material style

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-design-system#167]
### Observed behavior

We're currently using the old Material style of textboxes. In addition to having [proven UX issues](https://link.medium.com/hDuR66wnq1), it also leads to inconsistent vertical rhythm:

| ![image](https://user-images.githubusercontent.com/2367265/68414374-ec2d0a00-0144-11ea-9fd8-221f6785eaa6.png) |   ![image](https://user-images.githubusercontent.com/2367265/68414421-04048e00-0145-11ea-941c-7b580f79411c.png) |
|--|--|
| ![image](https://user-images.githubusercontent.com/2367265/68414411-fea74380-0144-11ea-8886-eb2809150f7b.png) |![image](https://user-images.githubusercontent.com/2367265/68414384-f0592780-0144-11ea-967a-6f628f8da4bc.png) |

### Expected behavior

upgrade to the new style:

![image](https://user-images.githubusercontent.com/2367265/68414532-3adaa400-0145-11ea-8fbf-0f9339897b3e.png)

### User-facing consequences

According to the study, this has improvements in three dimensions:

* Identifiability: The number of correct versus incorrect clicks
* Find-ability / scan-ability: The time it took a participant to find and click on a requested element
* Preference: Participants rank-ordered each text field variation

### Context

0.12.x

**Comment by radinamatic** [comment]
As mentioned in the #139, if we implement the text field background color, **contrast** becomes insufficient for labels and error message placeholders.

Label | Error
--- | ---
![2021-03-04_19-24-41](https://user-images.githubusercontent.com/1457929/110012625-01a64a00-7d21-11eb-8bc5-74a6d4822229.jpg) | ![2021-03-04_19-31-29](https://user-images.githubusercontent.com/1457929/110012651-09fe8500-7d21-11eb-858b-4c9b346256e0.jpg)

**Comment by indirectlylit** [comment]
duplicate of https://github.com/learningequality/kolibri-design-system/issues/124
