### ISSUE TITLE
icon button accepts both a tooltip and an aria label

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-design-system#168]
The `tooltip` and `ariaLabel` props should be consolidated into just `text` (for consistency with other button components) and made required

**Comment by rohitgeddam** [comment]
I would like to work on this!

**Comment by nucleogenesis** [comment]
Issue needs decisions around the proper acceptance criteria - ensuring that whatever changes are made to this effect are a11y focused

**Comment by AlexVelezLl** [comment]
I talked to Radinna and she suggeted not to have a fixed relation between a tooltip and an ariaLabel for cases where we need to announce something more specific as ariaLabel. But we agreed in that we can have the `tooltip` prop as fallback for the aria label when the prop `ariaLabel` is missing: https://github.com/learningequality/kolibri-design-system/issues/793.
