### ISSUE TITLE
KIconButton has redundant props

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-design-system#175]
## Expected behavior

The tooltip and aria label should always be the same for a `KIconButton`

## Actual behavior

There are separate props and aria label is not required:

```js
      ariaLabel: {
        type: String,
        default: null,
      },
      tooltip: {
        type: String,
        required: true,
      },
```

**Comment by marcellamaki** [comment]
Closing as duplicate of #168

**Comment by indirectlylit** [comment]
hah, and I filed those within a few days of each other 🤦
