### ISSUE TITLE
Netlify PR builds styling is broken

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri-design-system#181]
## Product
KDS

## Expected behavior

Netlify PR builds should represent production-like builds and be styled properly.

## Actual behavior

This is the KIconButtons I see on #165 's deployment (tooltips visible, buttons squared and white)

![screenshot-deploy-preview-165--kolibri-design-system netlify app-2021 02 25-10_14_41](https://user-images.githubusercontent.com/6356129/109349593-0fdcfd80-782b-11eb-974e-a33155ce457b.png)

But what I see when I pull and run locally:

![screenshot-localhost_4000-2021 02 26-12_06_58](https://user-images.githubusercontent.com/6356129/109349665-2f742600-782b-11eb-9203-79c22959c068.png)

Another in KButton (all white button formatting issues)

![screenshot-deploy-preview-165--kolibri-design-system netlify app-2021 02 26-12_01_40](https://user-images.githubusercontent.com/6356129/109349569-05baff00-782b-11eb-88d4-cd663c9c52f1.png)

Locally:

![screenshot-localhost_4000-2021 02 26-12_08_09](https://user-images.githubusercontent.com/6356129/109349769-503c7b80-782b-11eb-9e6c-ad71b23e8aaf.png)

## Steps to reproduce the issue
Go to #165 and check the button examples in the deployment preview.

Then pull locally and look at the same page side-by-side.

## Environment
- OS: Debian 10
- Browser version: Chrome 83.something

**Comment by indirectlylit** [comment]
hm unfortunately this seems to be true for production builds also

![image](https://user-images.githubusercontent.com/2367265/110055639-33fc7b00-7d12-11eb-89c6-7bb96511c9ad.png)
