### ISSUE TITLE
Would be nice if sidebar stayed static during navigation

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri-design-system#182]
## Product

KDS

## Desired behavior

When you click something in the sidebar you lose its state on navigation so if you scrolled way down and are specifically interested in the K*Components you have to scroll every time you want to change pages.

## (Optional) The Value Add

Fairly minor improvement to UX for team implementing KDS.

**Comment by indirectlylit** [comment]
yup - same as https://github.com/learningequality/kolibri-design-system/issues/17

> Fairly minor improvement to UX

major IMO! :)  taking a quick look now
