### ISSUE TITLE
Unit Testing Integration

### ISSUE THREAD

**Issue by Cronus1007** [learningequality/kolibri-design-system#190]
## Desired behavior
- Since the app is currently based upon Vue.js and is mainly a front end application so to enhance the code maintainability we can add the Cypress testing to the code repository as well as unit test cases based upon the `vue-test-utils`.

## Current behavior
- No such tests exist.
## (Optional) The Value Add
It will make the code more maintainable and will also automate the process of testing 
## (Optional) Possible Tradeoffs

# Add labels
task

**Comment by MisRob** [comment]
Closing as we've started with unit testing components already
