### ISSUE TITLE
Multi-select dropdown filters: Better handling for multiple selections and long text

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri-design-system#202]
## Product
All 

## Desired behavior
While unopened, multi-select dropdown filters should communicate to the user (1) how many selections have been made within the filter, and (2) what those selections are, without breaking the layout of the surrounding UI. These two things don't have to be shown to the user at the same time in compact spaces like dropdowns.

## Current behavior
<img width="630" alt="Screen Shot 2021-03-03 at 2 37 33 PM (1)" src="https://user-images.githubusercontent.com/6668144/112035025-640e9100-8afc-11eb-81f1-96729b088e74.png">

## (Optional) The Value Add
This will benefit any UI that has lists, tables, and search interfaces. Less visual clutter while still effectively communicating about the current filter state.

## Reference
[Slack thread](https://learningequality.slack.com/archives/CTG8XDTCL/p1614804101093700)

**Comment by MisRob** [comment]
We agreed to close this since some aspects have been fixed and some other may need some more thinking at first in the light of new interfaces in Studio
