### ISSUE TITLE
Icon precompilation: should not re-pre-compile everything every time

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri-design-system#205]
## Product

KDS

## Expected behavior

When I precompile icons, I'd like the option to not pre-compile icons that are already created. I can't think of the reason why the code is how it is but I think it was for testing.

## Actual behavior

When I precompile icons, it deletes all existing icons and generates 5000+ icons.

## Steps to reproduce the issue

`yarn precompile-svgs`

**Comment by indirectlylit** [comment]
I think it's to account for the unlikely but possible scenario of updates to existing icons?

We currently add a hash of the SVG to the vue component name. If we wanted to be clever we could somehow do a check on that...

**Comment by nucleogenesis** [comment]
Stale. Documentation explains the proper path forward for this and (IIRC) this has been changed a bit since this issue was made.
