### ISSUE TITLE
Update KDS for eventual support of H5P in Studio/Kolibri

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri-design-system#207]
## Product
K + S

## Desired behavior

See https://github.com/learningequality/kolibri/issues/7925

As a new resource type H5P needs an icon, colors, documentation, etc. 

## Current behavior

H5P content is not treated as a supported resource type

**Comment by jredrejo** [comment]
@MisRob @marcellamaki 
bumping this as it's causing errors now that need workarounds in kolibri https://github.com/learningequality/kolibri/pull/8885

**Comment by marcellamaki** [comment]
Thanks @jredrejo -- will add this for discussion at our next planning meeting!

**Comment by rtibbles** [comment]
One thing to ask in the discussion is which users we would still continue to show kind icons to instead of, or in addition to, learning activities icons.

**Comment by nucleogenesis** [comment]
This doesn't appear to be an issue any longer, closing.
