### ISSUE TITLE
Move HeaderTable and HeaderTableRow into design system

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-design-system#220]
Moving this placeholder issue from Kolibri repo to design system

----

@ralphiee22 commented on [Wed May 15 2019](https://github.com/learningequality/kolibri/issues/5487)

Move `HeaderTable` and `HeaderTableRow` from the coach reports plugin into the core components as mentioned here https://github.com/learningequality/kolibri-data-portal/pull/7#issuecomment-489178124.

**Comment by nucleogenesis** [comment]
Given the ongoing work with the KSortableTable component, we are adding tables to KDS without needing the extant coach header components mentioned here.
