### ISSUE TITLE
add documentation of supported jsdocs tags and conventions

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-design-system#222]
## Desired behavior

The readme should include documentation of how to write jsdocs for library components that will be correctly interpreted and rendered by the API extraction and rendering code

## Current behavior

Currently we link to https://vue-styleguidist.github.io/docs/Documenting.html

This is somewhat helpful but not a precise description of what tags and features are supported by KDS

## (Optional) The Value Add

Any dev can update KDS component jsdocs and have their changes easily reflected in the published documentation

**Comment by nucleogenesis** [comment]
Closing as we've not had much issue w/ the guidance linked as-is.
