### ISSUE TITLE
KImg component for accessible, responsive image rendering

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri-design-system#23]
Currently, some parts of Studio are using the Vuetify `VImg` component, which produces responsive images, but does so by setting a background image onto a `div` - this goes against good accessibility practices, and is something that @nucleogenesis did significant work to address in github.com/learningequality/kolibri

It would be good to port that responsive image work to a more general component to allow us to use accessible responsive images across our ecosystem.

**Comment by indirectlylit** [comment]
We also have a need for displaying images at fixed aspect ratios with consistent letterboxing behaviors. In particular, most of our cards assume 16:9 thumbnails, but this is not always the case and we need a consistent [letterboxing](https://en.wikipedia.org/wiki/Letterboxing_(filming)) display strategy for these.

refs:

* https://learningequality.slack.com/archives/C0LK8QS9J/p1558112430448200
* https://learningequality.slack.com/archives/C0LK8QS9J/p1562697036361300
* https://github.com/learningequality/kolibri/issues/3726
* https://github.com/learningequality/kolibri/issues/6185
* https://github.com/learningequality/kolibri/issues/5706

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri-design-system/pull/538
