### ISSUE TITLE
New Icons for Learning Activities

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri-design-system#232]
Following up from https://github.com/learningequality/kolibri/issues/7874 which was tracked as ready for review on the design side.

@khangmach can you please update this with:

- [ ] Links to the SVG icons
- [ ] Guidance on which, if any, existing icons will be removed in lieu of the new ones
- [ ] A mapping of `tokensForTheIcons` to the icons themselves - including any default colors. Additionally, note if the icon should flip when in rtl or not.

---

Dev Tasks (Acceptance Criteria):

- [ ] Add any new (custom) icon svgs to the `{KDS_ROOT}/custom_icons` directory
- [ ] Run `yarn precompile-svgs`
- [ ] Add all icons mapping to the `iconDefinitions.js` file 
- [ ] Run `yarn pregenerate` to generate a new `rstDefinitions` file
- [ ] (Optionally) follow up with a PR addressing this issue https://github.com/learningequality/kolibri-docs/issues/219 (or ping @radinamatic for review of this so she knows she can add them)

**Comment by jonboiser** [comment]
@nucleogenesis The SVGs can be pulled from the Figma files, if those are the final versions. Should I just go ahead and do that?

**Comment by nucleogenesis** [comment]
@jonboiser sure you or whoever takes this on can do that - but we'll need confirmation on, or preferably, some provided tokens/names for the icons themselves. Khang noted that some icons are two-toned and others aren't as well so they'll need to be distinguished. 

We'll also need noted here [which should be flipped in RTL](https://design-system.learningequality.org/icons/#i18n) which should be given in guidance by @khangmach or @jtamiace
