### ISSUE TITLE
Document props for `KContentRenderer`

### ISSUE THREAD

**Issue by sairina** [learningequality/kolibri-design-system#234]
## Product

Design System docs

## Expected behavior

Props for `KContentRenderer` need to be updated with jsdoc-formatted documentation for all props, including the recently-added `timeSpent` and `duration`

## Actual behavior

Props are not yet documented in a way that is parsed by the design system:

https://design-system.learningequality.org/kcontentrenderer/

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/2367265/118898185-f69f9680-b8d9-11eb-86d5-9144c984c57b.png">

**Comment by indirectlylit** [comment]
thanks @sairina – updated the scope of the issue slightly

**Comment by nucleogenesis** [comment]
KContentRenderer was migrated to Kolibri
