### ISSUE TITLE
Update learning activity icons to use colors from the token palette

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri-design-system#262]
## Product

All

## Desired behavior

The new learning activity icons are currently using arbitrary hex codes. There's a slight benefit for maintainability and consistency if we use tokens from our palette instead.

Proposed tokens & token aliases(?):
<img width="539" alt="Screen Shot 2021-09-20 at 11 53 36 AM" src="https://user-images.githubusercontent.com/6668144/134058327-18a7884b-0aa5-470c-9097-21f011f52b88.png">

**Comment by nucleogenesis** [comment]
This issue is a bit out of date - w/ the rebrand we've also changed the palette, so how that impacts the icons will be handled separately.

@jtamiace and @nucleogenesis will consider this while working on #540
