### ISSUE TITLE
create new KContentCard component

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri-design-system#263]
## Product
Definitely Kolibri, but likely KDP and/or Studio in the future

## Desired behavior
I think having a KContentCard component would be very helpful, especially as we move into the new 0.15 launch. (This does not need to be _for_ the launch, but I think having a KComponent to refactor with would be a good idea. 

## Current behavior
There are many different Content Cards and content grids that are used across kolibri. It's not ideal 😄 

## The Value Add
Having one flexible, abstracted card would be very useful for future dev work on Kolibri if we are going to continue to use cards. It would reduce the overhead for page changes, and it would also be easier to learn how one KComponent works, rather than mentally switching back and forth between getting multiple different cards to work. It would also ensure a consistent responsive experience.

While I am not very well-versed in the accessibility concerns, I also think that there is quite a bit of material available about how to make card elements accessible (the short version is, making the experience anything more than the bare minimum is actually quite nuanced), and I while I think the team will be working to make sure the cards meet some basic level of accessibility for the 0.15 launch, I think that investing the time in making this card a _great_ experience for learner who use assistive technologies is very worthwhile. (I have some bookmarked resources I can share if anyone is interested.)

Finally, I wonder about the value of having some "design patterns" for possible card layouts - which might also make this easier on the design side for new work as well - flexible, but with some constraints. Like... a handful of legos - arrange them however you want, in code of in design, but these are the legos we are working with. (I am open to other opinions on this!)

## (Optional) Possible Tradeoffs
- it might lock us into card designs we don't want, or might be too constraining 
- now that we have done 0.15, is refactoring this a good use of (very limited) developer hours?
- I don't actually know what the criteria are for "qualification to enter into the code library" so maybe this does not meet that standard!

**Comment by rtibbles** [comment]
Maybe the more general 'component-library' like ask here is a KCard component, rather than one specific to content cards?

This would also let it be generalized to display of channels, 'quasi-content' like coach generated quizzes and lessons, and card based listings of classrooms, groups, etc.

**Comment by MisRob** [comment]
Related https://github.com/learningequality/kolibri-design-system/issues/264

**Comment by AlexVelezLl** [comment]
Closing in favor of #445
