### ISSUE TITLE
Add an option to define a default `span` of all fixed grid items via `KFixedGrid` prop

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri-design-system#267]
## Product

Kolibri

## Desired behavior

It's possible to define a default `KFixedGridItem`'s `span` via a `KFixedGrid` prop (called `itemSpan` in the following example).

For example:

```jsx
<KFixedGrid numCols="12">
  <KFixedGridItem span="4" />
  <KFixedGridItem span="4" />
  <KFixedGridItem span="4" />
</KFixedGrid>
```

could be newly also defined as:

```jsx
<KFixedGrid numCols="12" itemSpan="4">
  <KFixedGridItem />
  <KFixedGridItem />
  <KFixedGridItem />
</KFixedGrid>
```

`itemSpan` would be treated as a default value for all three `KFixedGridItem`'s `span` values in this grid. If there's a `KFixedGridItem` with its own `span` value defined, such value would take preference over the default value for that particular item.

## Current behavior

`span` needs to be defined on `KFixedGridItem` and if it's not defined, the item will span the full width of the grid

## The Value Add

In Kolibri, we have the `CardGrid` component and use it in the following way:

**`CardGrid` type 1**
- Level 3+: 3 cards on a row
- Level 2: 2 cards on a row
- Level 1: 1 card on a row
- Level 0: 1 card on a row

| Level 3+ | Level 2 | Level 1 | Level 0 |
| --------- |  --------- |  --------- |  --------- | 
| ![Screenshot from 2021-11-02 12-51-34](https://user-images.githubusercontent.com/13509191/139841663-cb9584b9-457a-471a-854f-8330fffd433d.png) | ![Screenshot from 2021-11-02 12-55-59](https://user-images.githubusercontent.com/13509191/139841743-fdc8363e-4fad-4ad4-81c4-abe9fb3f044f.png) | ![Screenshot from 2021-11-02 12-56-31](https://user-images.githubusercontent.com/13509191/139841806-d77d24b1-9951-4cf7-98cf-ac8034457957.png) | ![Screenshot from 2021-11-02 12-56-31](https://user-images.githubusercontent.com/13509191/139841806-d77d24b1-9951-4cf7-98cf-ac8034457957.png) |

**`CardGrid` type 2**
- Level 3+: 4 cards on a row
- Level 2: 3 cards on a row
- Level 1: 2 card on a row
- Level 0: 1 card on a row

| Level 3+ | Level 2 | Level 1 | Level 0 |
| --------- |  --------- |  --------- |  --------- | 
| ![Screenshot from 2021-11-02 13-03-04](https://user-images.githubusercontent.com/13509191/139842681-4c396ebe-f360-4413-a9c6-47848768bf0e.png) | ![Screenshot from 2021-11-02 13-03-11](https://user-images.githubusercontent.com/13509191/139842703-605cd1d9-b5b0-4484-ad71-15af28642312.png) | ![Screenshot from 2021-11-02 13-03-19](https://user-images.githubusercontent.com/13509191/139842722-9483f4cf-02f7-4b94-a92d-e8c5d1f8d9a0.png) | ![Screenshot from 2021-11-02 13-03-31](https://user-images.githubusercontent.com/13509191/139842736-4276c5d1-12c7-4309-b0b8-b0f2a3786ad4.png) |

`CardGrid` is responsible for defining how many cards are displayed on one row and therefore, cards components don't need to contain any layout information in regards to its mother grid, which in this case makes implementation much simpler because:

1. when compared to the need to use the `span` attribute on `KFixedGridItem`, with this approach there is no coupling of card components to the grid component, so any of the cards can be used easily in any of those two grid types
2. it's much easier to define complex responsive behavior in one place when compared to having it spread across all cards components that are allowed to be used from within the grid

When I tried to use `KFixedGrid`/`KFixedGridItem` instead of `CardGrid`/`CardLink`, I found it challenging for these reasons. I think that having a possibility to define a default item span from within `KFixedGrid` would allow us to be more flexible overall and opened a way for being able to use `KFixedGrid` instead of `CardGrid`.

You can see Kolibri grid and cards [here](https://github.com/learningequality/kolibri/tree/release-v0.15.x/kolibri/plugins/learn/assets/src/views/cards)

## Possible Tradeoffs

I am not aware of any tradeoffs since this would be an alternative way of defining layouts. Any thoughts?

**Comment by MisRob** [comment]
@indirectlylit Thank you, I've just posted the screenshots and also tried to update the description to be more clear

**Comment by MisRob** [comment]
If we wanted to be fancy, maybe we could even try something like this?

```
<KFixedGrid numCols="12" :itemsSpans="[3, 3, 6]">
  <KFixedGridItem />
  <KFixedGridItem />
  <KFixedGridItem />
</KFixedGrid>
```

**Comment by sairina** [comment]
I believe this is a Kolibri issue that is could be directly affected by this update? https://github.com/learningequality/kolibri/issues/8988

**Comment by MisRob** [comment]
@sairina This is a proposal for a feature that we might implement or not, and we don't know yet exactly what API would that be, whereas https://github.com/learningequality/kolibri/issues/8988 seems to be rather a bug related to the usage of the grid that's not supported and might not still be supported in the future so I don't see the clear link. What did you mean by "directly affected"?

**Comment by sairina** [comment]
Oh that's helpful. I think I misunderstood this KDS proposal. I'll unlink the issues. Thanks!

**Comment by MisRob** [comment]
Closing since we'll have another component for cards display in a grid.
