### ISSUE TITLE
Add "auto" value to KFixedGridItem/KGridItem's "alignment" prop

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri-design-system#268]
## Product

Kolibri

## Desired behavior

Allow `'auto'` value in `KFixedGridItem`/`KGridItem`'s `alignment` prop and when `alignment` is `'auto'`, do not set `text-align` (like it happens when `alignment` is `'right'`, `'center'`, `'left'`) but instead set `dir=auto` on the grid item element.

## Current behavior

`text-align` is set on grid items all the time. Even when we set `dir=auto` on `KFixedGridItem`/`KGridItem`, it doesn't work properly because of conflicting with `text-align` defined in the grid item component, and we need to use a workaround [like for example unsetting `text-align` here](https://github.com/learningequality/kolibri/pull/8504/files#diff-37ca591b86347445814bb801f7a7b8994ecfa24421c484f6267f3d2f95526bfaR29-R36).

## The Value Add

No hacks will be needed anymore to make automatic directionality work for content in grid items which means that chances that accessibility works as expected will be higher  in regards to `dir=auto`.

## Comments

[Related Slack thread](https://learningequality.slack.com/archives/C023DNC5GCX/p1634568796212900)

**Comment by BabyElias** [comment]
Hey! Can I work on this issue?

**Comment by MisRob** [comment]
Hi @BabyElias, yes, thank you

**Comment by BabyElias** [comment]
Hey!
Just to inform, I have started working on this issue but am caught up currently due to my semester examinations. I'll generate a PR as soon as possible, once my exams are over next week.
Thank you for your time and patience :)

**Comment by lokesh-sagi125** [comment]
hey @AlexVelezLl  since there is no one assigned rn can i work on this issue?

**Comment by AlexVelezLl** [comment]
Hey @lokesh-sagi125! For sure! I will assign this to you. Please feel free to ask any question if needed 🤗.

**Comment by lokesh-sagi125** [comment]
hey @AlexVelezLl  i went through the code for this issue and feel like the mention issue has already been dealt with, it is accepting the auto value from the [common.js](https://github.com/learningequality/kolibri-design-system/blob/develop/lib/grids/common.js) file,
do you want me to add it directly to the file?

**Comment by MisRob** [comment]
@lokesh-sagi125 I am not sure I can understand exactly what you mean. Are you saying that this:

> when alignment is 'auto', do not set text-align (like it happens when alignment is 'right', 'center', 'left') but instead set dir=auto on the grid item element.

already works?

**Comment by lokesh-sagi125** [comment]
yes  @MisRob  when i tested it in playground and inspected it , there was no text-align being set and the div is being set `div=auto`
, i have attached an image of my console.![Image](https://github.com/user-attachments/assets/6e0195b1-0bd2-4709-aa22-ac47769685f0)

**Comment by lokesh-sagi125** [comment]
this was the acceptance criteria of the issue right?

**Comment by MisRob** [comment]
Thanks for checking this @lokesh-sagi125. Yes, it seems it already works as expected. Let me confirm some time later this week and we can probably close the issue then.

**Comment by lokesh-sagi125** [comment]
sure @MisRob

**Comment by MisRob** [comment]
@lokesh-sagi125 I confirm this has been resolved already in https://github.com/learningequality/kolibri-design-system/commit/c85e4d80e0759c16e68fc5435ee8ee572ece0c5d so will close the issue. Thank you for checking on this, either it was done after I opened the issue and we didn't link, or I missed it.

**Comment by lokesh-sagi125** [comment]
glad to know it was fixed:)
