### ISSUE TITLE
change KEmptyPlaceholder to KOptionalText

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-design-system#285]
## Product

Kolibri

## Desired behavior

`KEmptyPlaceholder` is always used with a `v-else` directive next to another text block.

We should have a `KOptionalText` component will either display the text or the existing `KEmptyPlacehlder` if it's an empty string, undefined, or null. 

## (Optional) The Value Add

Simplify product code

**Comment by rtibbles** [comment]
This has been addressed by #403 and updated in Kolibri in https://github.com/learningequality/kolibri/pull/10050
