### ISSUE TITLE
`KBreadcrumbs` has errors in mobile view for folders

### ISSUE THREAD

**Issue by sairina** [learningequality/kolibri-design-system#293]
## Product
Kolibri v0.15

## Expected behavior
There should not be any errors in the console when opening the Topics page (clicking into a channel) in mobile view.

## Actual behavior
When opening the Topics page in mobile view, everything loads, but there are errors involving `KBreadcrumbs` in the console.

## Steps to reproduce the issue
1. Log in as learner in mobile view
2. Click on Library
3. Click on a Channel
4. You should immediately see the errors in the screenshots below in the console once you have entered a channel

## Additional information
<img width="245" alt="Screen Shot 2022-01-13 at 10 21 40 AM" src="https://user-images.githubusercontent.com/13563002/149387193-5fa2cd03-bd0d-4bef-b756-4edc424b6d83.png">

<img width="245" alt="Screen Shot 2022-01-13 at 10 21 53 AM" src="https://user-images.githubusercontent.com/13563002/149387213-b14a2701-1306-48db-b8df-6a4a29d77296.png">

<img width="245" alt="Screen Shot 2022-01-13 at 10 22 42 AM" src="https://user-images.githubusercontent.com/13563002/149387316-6502fb7b-e57d-40db-bea6-b161ca303ea1.png">

<img width="489" alt="Screen Shot 2022-01-13 at 10 22 21 AM" src="https://user-images.githubusercontent.com/13563002/149387275-67db8c5f-513e-459f-a097-b6db0b357121.png">

## Environment
- OS: Mac
- Browser version: Chrome

**Comment by nucleogenesis** [comment]
Needs to be replicated.

**Comment by pcenov** [comment]
@radinamatic I confirm that this issue is not replicable in 0.16 beta6.

**Comment by radinamatic** [comment]
Closing as not extant anymore on Kolibri 0.16! 💥
