### ISSUE TITLE
Revisit KRadioButton Text Truncation

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri-design-system#302]
## Product
Kolibri
Reported by Radina here:
https://github.com/learningequality/kolibri/issues/8808
https://github.com/learningequality/kolibri/pull/8949
and in several other issues through 0.15 Kolibri testing

In some situations, it may make sense to have the text truncate, but in other places, wrapping might make more sense. i.e. network address truncation, vs. a long phrase vs. a long word (i.e. frequently in German)

i.e. 
![image](https://user-images.githubusercontent.com/17235236/151879000-b5b18802-5066-4e11-9dc4-6fafd7862719.png)

**Comment by nucleogenesis** [comment]
Noting that the truncation was added here https://github.com/learningequality/kolibri/pull/6830 - I personally think that the wrapping text I screenshotted during testing makes more sense in general. I don't see the value in eliding part of the radio button's label.

**Comment by marcellamaki** [comment]
I've opened [a follow up issue](https://github.com/learningequality/kolibri-design-system/issues/350) for the actual change, and will close this out as the decision has been made.
