### ISSUE TITLE
KButtonGroups hide shadows of buttons

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri-design-system#32]
Example in KDP Sync modal:

![image](https://user-images.githubusercontent.com/10248067/84307861-6e821000-ab12-11ea-8ce1-8d87725a29eb.png)

**Comment by indirectlylit** [comment]
I'm still seeing this in the 0.14 beta 3:

![image](https://user-images.githubusercontent.com/2367265/85078873-4df13000-b17a-11ea-8d00-e3e961c66d53.png)

**Comment by nucleogenesis** [comment]
I'm no longer seeing this in the `release-v0.14.x` branch - with confirmation from another we can close this again.
