### ISSUE TITLE
`KSortableTable` Component

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri-design-system#328]
## Overview
The `KSortableTable` Component is an update to work begun with `CoreTable` and `SortableHeader` to create a KDS Component that will  

1. Have an easy-to-use, standard sortable table experience
2. Work across Kolibri and KDP
3. Meet best practices for screen-reader accessibility

### Impact and Timeline
The feature is in support of design updates for 0.16, for the "change facility" feature where a sortable table is required. By addressing this problem one time in KDS, we will be able to use this component across our products.

This is a Q2 project that should be completed well in advance of 0.16, although it will be deployed with that release. 

### Working Assumptions
- CoreTable and SortableHeader will be useful references 
- This component will be useful across products, and will be easily reusable

### Out of Scope
- This component does not need to handle filtering or searching
- This component does not need to manage pagination

### Acceptance Criteria 
The **core purpose** of making this a KDS component is for accessibility. Therefore, accessibility best practices will be the major part of the acceptance criteria. The other major goal is that the use of this component _should not_ leave too much to the developer. The core pieces of accessibility criteria should be the default behavior (i.e. not requiring extra configuration) and not easily modifiable. 

#### MVP

- **Full compliance to accessibility criteria is the baseline for our MVP.**
- Documentation for the new component added to KDS site

#### Additional notes
- Specs of the visual design of the table (colors, fonts, spacing, etc.) _may be changed_ as needed in support of accessibility best practices, but any changes should be done in consultation with Jessica and Radina. Changes to the spec that are _not_ made in support of accessibility are a no.
- Implementation of this component in Kolibri is out of scope of this epic -- this is just about the creation of the component 

### Resources 
[Figma](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=194%3A2920)

External resources on Accessible Sortable Tables: 
[USWDS: Sortable Tables](https://designsystem.digital.gov/components/table/#sortable-table-rows)
[Inclusive Components: Sortable Tables](https://inclusive-components.design/data-tables/)
[Multi-column sortable tables](https://adrianroselli.com/2021/06/multi-column-sortable-table-experiment.html)

**Comment by MisRob** [comment]
May be related https://github.com/learningequality/kolibri-design-system/issues/220

**Comment by MisRob** [comment]
Closed by GSOC `KTable` project
