### ISSUE TITLE
Create prototype (non-accessible) SortableTable

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri-design-system#330]
### Overview 

This is an initial prototyping issue for the creation of a reusable `KSortableTable` component. For context, please see the epic. 

### Expect Component API 

The API should build on the current `CoreTable` and KDP's `SortableHeader`. This would likely require most of the existing props, although they could be renamed or shared (if a similar prop is currently used in both components). 

`header` and `body` slots can be used, as in `CoreTable`, so that the table can be created to suit the data being displayed.

Core Table's props
```
selectable: {
        type: Boolean,
        default: false,
        required: false,
      },
      emptyMessage: {
        type: String,
        default: null,
      },
```
SortableHeader's props 
```
title: {
        type: String,
        required: true,
      },
      column: {
        type: String,
        required: true,
      },
      pos: {
        type: String,
        default: 'right',
      },
      sort: {
        type: Boolean,
        default: true,
      },
```

During this stage, the visual design of the basic `CoreTable` component does not need to change. 

### Acceptance Criteria
- Creation of a prototype table that contains a sortable header which accurately updates table content when clicking sorting for ascending and descending
- At this stage, accessibility and design specifications are not acceptance criteria

**Comment by nick2432** [comment]
can i work on this?

**Comment by MisRob** [comment]
Hi @nick2432, I'm sorry, this is not ready to be developed yet. We recommend issues labeled as "help wanted" or "good first issue".

We currently have contributing opportunities in three repositories. You can see the contributing guidelines including links to issues suitable for contribution for each repository here:

- [Kolibri Contributing Guidelines](https://github.com/learningequality/kolibri/blob/release-v0.16.x/CONTRIBUTING.md)

- [Kolibri Design System Contributing Guidelines](https://github.com/learningequality/kolibri-design-system/blob/main/CONTRIBUTING.md)

- [Studio Contributing Guidelines](https://github.com/learningequality/studio/blob/unstable/CONTRIBUTING.md)

**Comment by MisRob** [comment]
Closed by GSOC `KTable` project
