### ISSUE TITLE
Kselect should provide the select event

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri-design-system#342]
## Product
This has been needed in KDP but it can be needed anywhere if the UI must know the user has selected again the same option (in KDP it should show a modal whenever the `custom` option is selected, now it's not possible because only the `change` event is available in KSelect)

## Desired behavior
Don't stop the `select` event provided KeenUISelect and let it be available in KSelect

## Current behavior
Currently KSelect only provides a `change` event

This issue should be done after #/339

**Comment by AlexVelezLl** [comment]
Hi! I was reviewing this, but I noticed that the `select` event emitted by `KeenUISelect` expose an options object with the `selected` property. But this property only changes for multi-selects, for the rest it is always set as true, however multi-select is not supported by `KSelect` 🤔 . So, should we change this property to return whether the selected option was previously selected, regardless of whether it is multi-select or not?

**Comment by rtibbles** [comment]
Fixed in #399 - it now produces a select event where the first value is the item selected (and in the case of multiselect, which I don't think we currently allow within KSelect - the second value is an object with a `selected` property saying whether it was selected or not).
