### ISSUE TITLE
KCheckbox and KRadioButton offer consistent API and resulting markup in regards to labels

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri-design-system#349]
## Product

All products

## Desired behavior

`KCheckbox` and `KRadioButton` have the same API and HTML output in regards to labels

## Current behavior

There are many differences between `KCheckbox` and `KRadioButton` labeling, in both their API and rendered raw output. Some examples:

### 1. Implicit vs. explicit labels

`KRadioButton` uses implicit labeling

https://github.com/learningequality/kolibri-design-system/blob/37dcf4f8db24d0afc5a72586bb35771dd29c8b1d/lib/KRadioButton.vue#L4-L24

whereas `KCheckbox` uses explicit labeling

https://github.com/learningequality/kolibri-design-system/blob/37dcf4f8db24d0afc5a72586bb35771dd29c8b1d/lib/KCheckbox.vue#L57-L70

### 2. Required vs. optional properties

 `KRadioButton` requires the `label` prop

https://github.com/learningequality/kolibri-design-system/blob/37dcf4f8db24d0afc5a72586bb35771dd29c8b1d/lib/KRadioButton.vue#L74-L77

whereas `KCheckbox` doesn't require it

https://github.com/learningequality/kolibri-design-system/blob/37dcf4f8db24d0afc5a72586bb35771dd29c8b1d/lib/KCheckbox.vue#L89-L92

### 3. Default slots

`KCheckbox` supports passing label content via the default slot (even though it won't get properly rendered as `<label>` https://github.com/learningequality/kolibri-design-system/issues/347)

https://github.com/learningequality/kolibri-design-system/blob/37dcf4f8db24d0afc5a72586bb35771dd29c8b1d/lib/KCheckbox.vue#L46-L50

whereas `KRadioButton` doesn't support it

### 4. Visually hiding the label

`KCheckbox` offers an option to visually hide a label via `showLabel` property

https://github.com/learningequality/kolibri-design-system/blob/37dcf4f8db24d0afc5a72586bb35771dd29c8b1d/lib/KCheckbox.vue#L62

whereas there's not such an option for `KRadioButton`

## The Value Add

- As both these components model `<input>` (and to some extent `<label>`), having so many differences in common areas of their interface makes using and learning to use them more difficult. A consistent interface will help this.
- Helpful in scenarios we need to switch dynamically between them while using the same label

## Possible Tradeoffs

I'm not aware of any

## Note

If we decide to work on this, see https://github.com/learningequality/kolibri-design-system/issues/348 first please, where I proposed several `KRadioButtons` updates in regards to input labels that, if we decide to implement them. would by means of this issue also affect work on `KCheckbox`.

**Comment by nucleogenesis** [comment]
It doesn't look like it would - but this doesn't seem likely to break existing uses in our products since the API layout is being extended rather than changed -- am I missing anything in that regard?

**Comment by MisRob** [comment]
I split things around checkboxes and radio buttons into more related issues

**Comment by MisRob** [comment]
And yes, I too think that the way we use radio buttons and checkboxes in our products should be compatible even after this update.

**Comment by MisRob** [comment]
Related https://github.com/learningequality/kolibri-design-system/issues/187

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri-design-system/pull/380
