### ISSUE TITLE
Use wrapping rather than Text Truncation on KRadioButton

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri-design-system#350]
## Product
Kolibri, potentially Studio?

## Desired behavior
Rather than using text truncation on radio buttons (encountered/needed mainly on small screens, wrap the text so that all text is displayed)

## Current behavior
Currently, the text truncates with an ellipsis

## (Optional) The Value Add
This will prevent the potential loss of important information to users on smaller screens (especially if the radio button is a phrase or sentence, rather than one or two words, like a yes/no choice)

## (Optional) Possible Tradeoffs
There might be scenarios where the truncation would make more sense? So far, we have not encountered any _definitive_ scenarios, however.

**Comment by marcellamaki** [comment]
This can be a starter issue for our new colleagues, but should be done with support for proper context about KDS. The task itself is quite manageable, but navigating the relationship between working in develop on KDS and Kolibri, testing, etc. should be done with guidance/support.

**Comment by MisRob** [comment]
Related:
- https://github.com/learningequality/kolibri-design-system/issues/348
- https://github.com/learningequality/kolibri-design-system/issues/349

**Comment by MisRob** [comment]
As suggested in the related issues, labels in general (=> text truncation or wrapping etc. as well) wouldn't ideally be controlled so tightly by KDS - we could pass anything as a label from products (perhaps, we could keep some truncation logic for the sake of simplicity, but in that case, it should be optional and easily overridable)

**Comment by marcellamaki** [comment]
Closed in https://github.com/learningequality/kolibri-design-system/pull/380
