### ISSUE TITLE
Upgrade Netlify build image

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri-design-system#359]
On November 15, 2022, Netlify will end support for Ubuntu Xenial image that we happen to use for our documentation builds. We need to upgrade:

> Select a site name above to access specific site settings in the Netlify UI where you can change the site’s build image.

Provided by @DXCanas:

![Screenshot from 2022-09-07 13-51-43](https://user-images.githubusercontent.com/13509191/188871936-8d3bc4c0-ca48-4b02-b47c-9c5be35dd64e.png)

**Comment by indirectlylit** [comment]
The [migration guide has helpful notes](https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239?_hsmi=224840388&_hsenc=p2ANqtz-8IqDOhh9GzwRZuxzu4GZwLRXKI3AyVQ4PbwAEiANbLXs_uPSr2uTk1QyTphJgHcDVxpc1sKdDmQWJakcmi31Psua7HKQ#how-can-i-run-a-test-build-with-the-new-image-6) on how to run a test deploy with the new image:

**Comment by rtibbles** [comment]
This has now been updated. There were no issues in building in the updated image.
