### ISSUE TITLE
Create KDatePicker and KDateRange components

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri-design-system#360]
## Product

- The components will be used in Kolibri in selecting date ranges for exporting logs
- The components will be created by [migrating](https://github.com/learningequality/kolibri-data-portal/blob/staging/kolibri_data_portal/assets/src_home/views/DataPage/CustomDateFilter.vue) functionality from Kolibri Data Portal
- [Designs](https://www.figma.com/file/SgTZugaKkES68aipU5dCk8SR/Github-issues-%26-random-fixes) that will be implemented in Kolibri

Example:
![Screenshot from 2022-09-09 08-50-13](https://user-images.githubusercontent.com/819838/189390786-977dd592-80d7-4f5f-bfc4-867d2d5ecdac.png)

## Desired behavior

- The PR should target the `develop` branch for integration into Kolibri's `develop` branch; note we won't be able to update KDP until KDP is updated to use the latest Kolibri from its `develop` branch
- The `KDatePicker` component:
  - Should accept a required `selectionLevel` prop that will only allow `month` level to begin with, allowing future enhancements to possibly allow `day` level selection
  - Should allow use with `v-model` which will allow setting a default value
  - Should accept a `firstAllowedDate` prop that constrains the selection to after the date, disabling dates prior
  - Should accept a `lastAllowedDate` prop that defaults to the current date and constrains the selection to before that date, disabling dates after
  - Should implement 2 `KSelect`'s, one for month and one for year, when the `selectionLevel` is `month`, and wrap them in a `<fieldset>`
  - Should accept a `legendText` prop that will show in a `<legend>` tag, e.g. "Start" or "End", prepended to `<fieldset>`
  - Should have a page for it added to the documentation
- The `KDateRange` component:
  - Should have no default for the `firstAllowedDate` prop
  - Should accept a prop for a default start date selection
  - Should implement two `<KDatePicker>` instances for start and end date selection, sending the default start date to `v-model` of the start `<KDatePicker>`
  - Should define a slot to allow a subtitle/description field to appear below the modal's title
  - Should define a `title` string prop to customize the modal's title
  - Should define a `submitText` string prop to customize the submit button
  - Should replace `Start of` and `End of`, in the existing component, with translatable strings removing `of`
  - Should ensure that the <kbd>TAB</kbd> order between `KDatePicker` components is correct
  - Should have a page for it added to the documentation

## (Optional) The Value Add

Adds a rich date range selection for reuse across the Kolibri ecosystem, and will be immediately implemented in Kolibri and KDP

## (Optional) Possible Tradeoffs

To start this component would only allow selection down to the month level, but it could be further customized later to support full date selection. To prevent unnecessary refactors, we added a `selectionLevel` to `<KDatePicker>` in the event we add `day` level selection in the future.

**Comment by radinamatic** [comment]
Date pickers can be tricky to implement accessibly, I recommend reading this recent article that collects good examples that take accessibility into account:

https://www.digitala11y.com/accessible-datepickers-roundup/

**Comment by bjester** [comment]
Thanks @radinamatic! This isn't your typical date picker, since it isn't calendar based. This initial implementation only allows selection to the month level, so it will implement 2 `KSelect` for year and month.
