### ISSUE TITLE
KImg: Kolibri Fly!

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri-design-system#373]
## Summary

Truthy `kolibriFly` prop renders the Kolibri logo into the `KImg`. This overrides the `src` specified

## Epic

- https://github.com/learningequality/kolibri-design-system/issues/368

## Acceptance criteria

- [ ] Setting `kolibriFly` to `true` renders the Kolibri logo into the component
- [ ] Any set `src` is overridden

## Linked issues
  
- **Blocked by**
  - https://github.com/learningequality/kolibri-design-system/issues/369
  - https://github.com/learningequality/kolibri-design-system/issues/370

**Comment by MisRob** [comment]
Some KDS and products source files with the logo
- https://github.com/learningequality/kolibri-design-system/blob/develop/docs/common/DocsPageTemplate/SideNav/kolibri-logo.svg
- https://github.com/learningequality/studio/blob/unstable/contentcuration/contentcuration/frontend/shared/views/KolibriLogo.vue
- https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/views/CoreLogo/index.vue

**Comment by ShivangRawat30** [comment]
I would like to work on this issue.

**Comment by MisRob** [comment]
Hi @ShivangRawat30, good choice, this is IMHO the most fun issue in KDS. I'm sure that the team will love it :)

**Comment by MisRob** [comment]
Note that the specification here was changed to creating a new component, `KLogo` instead. https://github.com/learningequality/kolibri-design-system/pull/460#pullrequestreview-1651978076

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri-design-system/pull/460
