### ISSUE TITLE
KRadioButton redundant v-model / value

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri-design-system#379]
Originally reported by @rtibbles on Slack:

> I was reviewing 
> [@José](https://learningequality.slack.com/team/UA1H0MMRQ)
> 's [KDP PR](https://github.com/learningequality/kolibri-data-portal/pull/417/) and came across something in the API of KRadioButton that concerned me. In [the documentation](https://design-system.learningequality.org/kradiobutton/#props) (and in the code) it appears that the way it is used is to bind the value prop at the same time as using v-model  - given that v-model is [a shorthand for two way data binding](https://v2.vuejs.org/v2/guide/components.html#Using-v-model-on-Components) of the value prop, this is really confusing. Apparently it works, but it seems susceptible to order effects (if you put the v-model after the value binding in the component instantiation, my guess is that it might not work any more).
> What seems to be the issue is that the currentValue prop should be the value prop and what is now the value prop should be the itemValue prop or somesuch - but this would also require updating all uses of KRadioButton to just use v-model. (edited)

Adding on - the `currentValue` prop is the prop saying "what is the current value of the group of KRadioButton's this instance is in?" which translates to "am I the radio button that is checked?" - it answers that question by comparing the `currentValue` of the set of buttons and sees if it is equal to the `value` -- which is the unique identifier for the instance of KRadioButton. 

As Richard noted, this seems not to cause any issues as it is - but it _is_ certainly a confusion API decision.

I think we should deprecate it to give ourselves time to weed the stuff out of Kolibri. If we get a reminder in the dev server logs we might feel inclined to clean up the KRadioButtons as we go rather than asking someone to just go through the codebase to do it all themselves which seems more likely to cause regressions.

**Acceptance Criteria**

- [ ] Add a deprecation notice so that it shows up in the next release indicating that `KRadioButton `value` prop is deprecated. Please use the `buttonValue` prop instead.
- [ ] Add the `buttonValue` prop and configure `KRadioButton` to use that in lieu of `value`.
- [ ] Create an issue in each Product's repository (KDP, Kolibri and Studio), add it to the backlog, to verify before upgrading KDS whether or not they are using the soon to be deprecated `value` prop in KRadioButton.
- [ ] Target your Pull Request to the `main` branch

**Comment by ShivangRawat30** [comment]
I would like to work on it.

**Comment by MisRob** [comment]
Hi @ShivangRawat30, I just assigned you two other issues so I will leave this one unassigned for now. As soon as you're done with the other two (or if you decide you won't work on some of them), please remind yourself here again in case you will still be interested in working on it.

**Comment by BabyElias** [comment]
Hey @MisRob!
I would like to work on this issue if it isn't being worked upon by anyone else so far. Thanks :)

**Comment by LianaHarris360** [comment]
Hey @BabyElias I'll be happy to assign you to this issue. If you have any questions or need any clarifications, please feel free to ask. Thank you!

**Comment by BabyElias** [comment]
Hey! So I just began working on this issue, and I had a few doubts.
1. Where should I add the deprecation notice? In the documentation itself?
2. The develop branch is no longer used in this repo, so should I create a develop branch of my own or target the PR to main branch?

**Comment by LianaHarris360** [comment]
> 1. Where should I add the deprecation notice in the documentation?

The deprecation notice should be added to the `Changlog.md` file. Mark the `Breaking` field as yes and ensure guidance is provided on updating the `KRadioButton` component to use `buttonValue` instead of the `value` prop. Also, please add the new item to the "Upcoming version" section of the Changelog.

> 2. The develop branch is no longer used in this repo, so should I target the PR to main branch?

Yes, please target the main branch instead of develop. I will update the Acceptance Criteria in this issue to reflect that.

> 3. How are issues added to backlog in the repositories mentioned above?

On the side panel, when selecting `Projects`, a list of projects will appear. Choosing `Iteration Backlog` will add the opened issue to the backlog, allowing the entire team to view it and take the necessary actions before updating KDS in other repositories. As KDP is a private repository, I will take care of creating those issues once the PR to address this is opened in KDS.

 It's no problem at all, thank you for your contributions! If you have any more, feel free to ask anytime. cc'ing @MisRob in case I've missed anything.

**Comment by BabyElias** [comment]
@LianaHarris360 As much as I could understand from the resources I found, the iteration backlog is available to Members of the organisation and not contributors. Apologies in advance if I am wrong, but can you let me know if this is true or not?

**Comment by LianaHarris360** [comment]
Yes, I believe that is correct. I will take care of creating those issues and adding them to the iteration backlog. The org's team members will address those issues before upgrading KDS in other repositories.

**Comment by BabyElias** [comment]
@LianaHarris360 I have created a PR for the same. 
This PR also contains commits for another issue (#479) and am waiting for that PR (#482)  to get merged before this PR so that no merge conflicts arise. Thank you for your patience.

**Comment by BabyElias** [comment]
Raised new PR #485 as had to close the previous PR due to merge conflicts.

**Comment by BabyElias** [comment]
@LianaHarris360 Updated PR #485 with the suggested changes. 
Thank you for your time and patience :)
