### ISSUE TITLE
KDS: Changelog between kolibri major versions

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri-design-system#428]
## Product
Any kolibri plugin with frontend code would benefit from this

## Desired behavior
After every new major of kolibri, all the plugins that have frontend parts need to be updated. Being KDS the core of the frontend, it would be really  useful to know what are the most important changes.

The list might have a list of things that are different between the previous and the new version of kolibri on the KDS side, something like:
- New components
- Removed components
- New API (props, events, etc) in existing components
- Breaking changes 
- Needed changes in dependencies, configurations for tests, etc.
- New recommended best/common practices when composing with different components (like those involving in the past Immersive pages, CoreBase, etc.)

For this purpose, there is no need to have the deep details current releases notes have, as this is not intended for KDS developers, but by kolibri developers who have KDS as a tool

## Current behavior
When a new kolibri version appears, I need to go through all the KDS releases happening between the version included in the previous kolibri version and the new, trying to extract information of the things that have changed for an external user of the library/API. Quite often, without the context of internal KDS work, these changes are hard to understand and breaking changes are not well detected.

## The Value Add
Non KDS developers working on kolibri frontend stuff will have happier working hours.

## Possible Tradeoffs
Time consuming and probably it'll be hard to find a solution that serves everyone.
Also, noticing this kind of changelog would be useful for Studio devs, but they don't need it to be matched with  kolibri releases.

**Comment by MisRob** [comment]
Done!
