### ISSUE TITLE
KDropdownMenu: unexpected behavior in "Facility Settings" view

### ISSUE THREAD

**Issue by thanksameeelian** [learningequality/kolibri-design-system#432]
## Product
Kolibri

## Expected behavior
"Option" dropdown will open below the container if there is space available on the page.

## Actual behavior
"Option" dropdown opens upward, inside parent container, regardless of space available.
![dropdown opens up](https://user-images.githubusercontent.com/43046460/232560863-6fe260ed-11e6-4367-b2f7-5b84be642180.png)

## Steps to reproduce the issue
Navigate to: Kolibri -> "Facility" tab -> "Facility Settings" subtopic -> "Option" dropdown -> open dropdown

## Additional information
📌 **GENERAL INFO:** over time, issues/bugs have arisen with our usage of vendored KeenUI files - we've struggled to keep up to date with source code without breaking borrowed components we'd already modified, and that has led to [some low-priority but cascading dev problems](https://docs.google.com/presentation/d/1KuhX88dv3bQakkpiPTDzWdORf4gV7jOzL-o9nwcnfb0/edit?usp=sharing). after internal debate, we've made the decision as a team to consider our forked KeenUI files to be fully our own. as we need to make changes to the components moving forward, we'll make those changes directly without concern for maintaining compatibility with the KeenUI codebase, which continues to change independently [(this same description soon to be included in KDS docs).](https://github.com/learningequality/kolibri-design-system/blob/cabbfbd4bbdc5d2f192cc276a61654cc4d2036ee/dev_docs/06_misc.md#keen-ui-vendored-files) 📌

potential solution referenced by @akolson: `we could achieve this behavior by adding support for the constrainToScrollParent  prop in KDropdownMenu . This is a Keen Ui's UiPopover prop that by default is set to true to prevent overflows. Under the hood, we are using it to support the KDropdownMenu component. I think it would be a good to have an override to the default behavior.` + helpful KeenUI reference:
![KeenUI reference](https://user-images.githubusercontent.com/43046460/232563319-ed265a98-ce07-4dad-a296-32ef39a9bbfd.png)

## Environment
- OS: Mac Monterey
- Browser version: Chrome 112.0.5615.49

**Comment by kafukoM** [comment]
Would like to be assigned to handle this issue.

**Comment by MisRob** [comment]
Hi @kafukoM, thanks for volunteering, I will assign you

**Comment by galovdev** [comment]
Can I work on this issue? @MisRob

**Comment by MisRob** [comment]
Hi @galovdev, thanks for volunteering. This is already assigned to @kafukoM. Please find [a "help wanted" issue with no assignee](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+no%3Aassignee&type=issues).

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri-design-system/pull/586 and  https://github.com/learningequality/kolibri/pull/12015
