### ISSUE TITLE
Add KTextTruncator component

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri-design-system#450]
## Product

Kolibri, Studio

## Summary

In Kolibri, we have `TextTruncatorCss` component. It would be useful in Studio as well (https://github.com/learningequality/studio/issues/4086, https://github.com/learningequality/studio/issues/4166).

Move `TextTruncatorCss` to this repository and rename it to `KTextTruncator`. Create a draft documentation page with some basic guidance on using it. Additionally, make sure that `KTextTruncator` works in RTL (right-to-left) languages (you can see https://github.com/learningequality/studio/pull/4288 for how to achieve it)

## Acceptance criteria

- [ ] It supports RTL
- [ ] It is sucessfuly used in at least one place in Kolibri
- [ ] (can be done as follow-up) It has a draft documentation page

## Outside of scope

There is no need to be replacing all `TextTruncatorCss` occurrences in Kolibri by `KTextTruncator` in the scope of this issue, only one is needed though to test that everything is okay. Neither it needs to be used in Studio. These could be follow-up tasks.

**Comment by MisRob** [comment]
See developers documentation
- Creating a component: https://github.com/learningequality/kolibri-design-system/blob/develop/dev_docs/03_how_to_update_library.md
- Creating a documentation page for a component https://github.com/learningequality/kolibri-design-system/blob/develop/dev_docs/04_how_to_update_docs.md#create-a-documentation-page-for-a-new-component

**Comment by MisRob** [comment]
This is reserved for contribution (was open as a follow-up to already merged contribution)

**Comment by muditchoudhary** [comment]
@MisRob Okay I understand the issue. Could you please assign it to me?

**Comment by MisRob** [comment]
Hi @muditchoudhary, great, it's all yours, thank you

**Comment by MisRob** [comment]
@muditchoudhary It'd be best if you started working in this repository and as soon as you feel you're ready for

> _It is sucessfuly used in at least one place in Kolibri_

please let me know and I will provide a bit of guidance as it might be tricky for the first time due to some problems with `yarn link` we recently discovered.

**Comment by muditchoudhary** [comment]
> It'd be best if you started working in this repository and as soon as you feel you're ready for

Yeah, sure! I have set up the local env. no issue with it. 

> please let me know and I will provide a bit of guidance as it might be tricky for the first time due to some problems with `yarn link` we recently discovered.

Sure, I'll let you know if I get into some issue that I cannot resolve. Thanks for telling about the yarn issue.

**Comment by MisRob** [comment]
@muditchoudhary Okay. I realized we even have an issue where you can find out the description of problems with `yarn link` (there's also a workaround with `yarn run build` and `yarn run python-devserver` mentioned in one of them): https://github.com/learningequality/kolibri/issues/10809

There's also another pretty simple workaround but let's look at it in case you can't move on with above.

**Comment by muditchoudhary** [comment]
Hello @MisRob I have copied the `TextTruncator.vue` into the `lib` but there are two dependency functions that are in `kolibri` but not in `kolibri-design-system`.

```
  import responsiveElementMixin from 'kolibri.coreVue.mixins.responsiveElementMixin';
  import commonCoreStrings from 'kolibri.coreVue.mixins.commonCoreStrings';
  ```
  
`responsiveElementMixin` is imported from `KResponsiveElementMixin` which is present in `kolibri-design` So, I think I can get this in `kolibri-design` but `commonCoreStrings` is only present in `kolibri`. 

So how do I get this `commonCoreStrings` into `kolibri-design`?

  
  I have tried to find other issues for reference where someone added or updated a component but did not find any.

**Comment by MisRob** [comment]
Hello @muditchoudhary, we're moving `TextTruncatorCss`, not `TextTruncator`

**Comment by MisRob** [comment]
`TextTruncator` is not in the codebase anymore

**Comment by muditchoudhary** [comment]
> Hello @muditchoudhary, we're moving `TextTruncatorCss`, not `TextTruncator`

Ohh yeah! haha I got confused. Thank you! 

I did not sync my local `kolibri` after PR.

**Comment by muditchoudhary** [comment]
Hello @MisRob I'm almost done with solving the issue, but there is a minor issue when I'm testing the KTextTruncator on Kolibri app. However, that issue does not come when trying in kolibri-design-playground.

The ellipsis is added a little forward from the last word. 

| With TextTruncatorCss | With KTextTruncator |
|---------|------|
| ![image](https://github.com/learningequality/kolibri-design-system/assets/74391865/74e256b9-f492-4670-9ba9-5505489f4bd7) | ![image](https://github.com/learningequality/kolibri-design-system/assets/74391865/68514085-9991-40ee-afb2-f3c91e233422) |

Tested on: Monitor with 1024x768 size

### What I think could be the issue
With KTextTruncator there is some **right padding** but with TextTruncatorCss there is **no right padding.**

| With TextTruncatorCss | With KTextTruncator |
|---------|------|
|![image](https://github.com/learningequality/kolibri-design-system/assets/74391865/721a3f56-7f4a-4468-a564-aae6461b6ae3) | ![image](https://github.com/learningequality/kolibri-design-system/assets/74391865/f2a82339-5a33-4a4a-9527-5f934522421a) |
 
 
 I used `yarn link` process to install this `KTextTruncator` into `Kolibri`.

**Comment by MisRob** [comment]
Hi @muditchoudhary, thanks for staying in touch, this is helpful.

I think you can feel free to adjust `KTextTruncator` code to work as expected in Kolibri (that is, without the gap)

**Comment by MisRob** [comment]
Also, you could see if there are some styles in Kolibri that could be causing this unexpectedly and will need to be removed as we're introducing `KTextTruncator`. However as mentioned, introducing it at all places in Kolibri is not in the scope of this issue (could be done as a follow-up) so testing just a few places and ensuring it works reliably there is sufficient.

**Comment by MisRob** [comment]
Let me know if this helps. If not, you could open a draft PR with your work in progress and we can have a look at code together

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri-design-system/pull/464
