### ISSUE TITLE
Add icon for "pending" download status

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri-design-system#458]
Currently the icon for pending on the downloads page is wrong - it is using the "stopwatch" style timer - and this icon needs to be added to KDS

See Figma https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?type=design&node-id=2626-29822&mode=design&t=A4F7ol6Qqmz1dseF-0

**Comment by nick2432** [comment]
can i work on this?

**Comment by MisRob** [comment]
Hi @nick2432, thank you! This was assigned to @marcellamaki but it's been a long time and doesn't seem to be in progress. @marcellamaki do you consider this to be suitable for contribution?

**Comment by marcellamaki** [comment]
Yes, thank you @MisRob for following up on this. @nick2432, I apologize that I missed this. Yes, this would be suitable for contribution and can be reassigned.

I'm not sure if you will be able to see the linked figma, but the icon to be added is this one: 
<img width="200" alt="Screenshot 2024-01-10 at 10 56 05 AM" src="https://github.com/learningequality/kolibri-design-system/assets/17235236/a230dd01-1d12-492a-a37b-abbde76bc2cc">

You can read [the developer documentation about adding icons](https://github.com/learningequality/kolibri-design-system/blob/main/dev_docs/05_icons.md) to get started, and post here with any follow up questions you have. (I imagine you will have some questions). 

Thank you!

**Comment by nick2432** [comment]
Hey @marcellamaki , first of all, sorry to disturb you, but I'm really confused. Where should I add 'pending'? I've read the related documents many times, but I'm still confused. Should I add 'pending' in the iconDefinitions.js file in the KolibriIcon object? Also, the icon you are showing seems to be the same as the schedule icon. If you can help in any way, please assist me.I've contributed to the backend, but this specific part seems a bit confusing to me.
