### ISSUE TITLE
Make KResponsiveWindow mixin show deprecation warning

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri-design-system#459]
We recently implemented `useKResponsiveWindow` composable that should replace [`KResponsiveWindow` mixin](https://github.com/learningequality/kolibri-design-system/blob/release-v1.5.x/lib/KResponsiveWindowMixin.js) (that will be removed one day).

To make sure that we don't introduce `KResponsiveWindow` mixin to new places in products consuming Kolibri Design System, it should show a deprecation console warning with a message guiding developers to use `useKResponsiveWindow` composable instead.

**Comment by ShivangRawat30** [comment]
can I work on this issue ?

**Comment by MisRob** [comment]
Thanks @ShivangRawat30. assigning you.

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri-design-system/pull/463
