### ISSUE TITLE
Make decisions about documenting button spacing and KButtonGroup

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-design-system#46]
Currently the buttons page does not mention spacing between buttons or the new `KButtonGroup` component

**Comment by nucleogenesis** [comment]
@jtamiace @indirectlylit Marking this for an upcoming patch since we can update the docs and our public deployment of them without concern for library code release

**Comment by nucleogenesis** [comment]
@jtamiace I'm closing this because it looks like it's resolved: https://kolibri-design-system.netlify.app/kbuttongroup/

**Comment by jtamiace** [comment]
Ah, great, I was wondering
