### ISSUE TITLE
Optimize `useKWindowDimensions` performance

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri-design-system#461]
## Summary

In `useKWindowDimensions`, we read `window.innerWidth/Height` on each `resize` event

https://github.com/learningequality/kolibri-design-system/blob/9ea4bae765fb3f0270c3c764c88cb44206147cc7/lib/useKWindowDimensions.js#L45

https://github.com/learningequality/kolibri-design-system/blob/9ea4bae765fb3f0270c3c764c88cb44206147cc7/lib/useKWindowDimensions.js#L25-L26

This is not good performance-wise since [reading innerWidth/Height causes layout/reflow](https://gist.github.com/paulirish/5d52fb081b3570c81e3a#getting-window-dimensions).

It'd be good to debounce the event handler calls so that `innerWidth/Height` is not read so often.

`lodash/debounce` is available in this repository for that purpose.

## References

- > If the resize event is triggered too many times for your application, see [Optimizing window.onresize](https://web.archive.org/web/20220714020647/https://bencentra.com/code/2015/02/27/optimizing-window-resize.html) to control the time after which the event fires. (https://developer.mozilla.org/en-US/docs/Web/API/Window/resize_event)

- https://medium.com/@vaibhavar/ui-performance-window-resize-handler-debouncing-2ec5f7432165

**Comment by Jaspreet-singh-1032** [comment]
Hi @MisRob, Please assign this issue to me.

**Comment by MisRob** [comment]
Thanks @Jaspreet-singh-1032, assigning you
