### ISSUE TITLE
The `yarn dev-only` misspelled in `01_getting_started.md`

### ISSUE THREAD

**Issue by muditchoudhary** [learningequality/kolibri-design-system#474]
## Product

In the **Design System** getting started docs `01_getting_started.md` the command `yarn dev-only` is misspelled. It should be `yarn _dev-only`

## Additional information

In the docs
![image](https://github.com/learningequality/kolibri-design-system/assets/74391865/31506545-0bb7-403b-9829-670aa3fa0451)
In the package.json
![image](https://github.com/learningequality/kolibri-design-system/assets/74391865/e191e6de-7b9c-4498-9926-af43aff93b44)

**Comment by MisRob** [comment]
Thanks for reporting @muditchoudhary!

Perhaps it'd be best to rename the command in package.json from `_dev-only` to `dev-only` as it's simpler to type.

**Comment by BabyElias** [comment]
Hello @MisRob !
Can I work on this issue?

**Comment by akolson** [comment]
Hello @BabyElias. Yes, you can. Thanks. 
Please be sure to let us know in case you need any support along the way.
