### ISSUE TITLE
Merge the current dependabot PRs

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri-design-system#477]
There are several dependabot PRs, some of them with possibly breaking changes. They need to be merged, tested, and relevant KDS code updated if needed. Note that we don't want to merge all dependabot PRs - PRs related to packages listed in https://github.com/learningequality/kolibri-design-system/issues/495 can be closed.

**Comment by MisRob** [comment]
This is currently blocked, I will open some related issues first

**Comment by rtibbles** [comment]
Closing this in preference to assigning the individual PRs for review.
