### ISSUE TITLE
Broken "develop" branch link

### ISSUE THREAD

**Issue by BabyElias** [learningequality/kolibri-design-system#479]
## Current behavior
The "develop" branch no longer exists on the kolibri-design-system repository, while it is mentioned in the Readme.md file and also, has a broken link addressing the same on https://develop--kolibri-design-system.netlify.app/
![image](https://github.com/learningequality/kolibri-design-system/assets/95405559/b7ecf724-e1ca-48e1-91cd-251011bd67e4)
![image](https://github.com/learningequality/kolibri-design-system/assets/95405559/ab131180-80d4-4117-babd-ec3670923c5e)

## Desired behavior
References of the branch should be removed in case the branch no longer exists Or new link should be provided if the branch exists.

**Comment by MisRob** [comment]
Ah yes, I made some changes to branches, and didn't realize these places need to be updated. Thanks for reporting!

This section in the README
![Screenshot from 2023-10-26 06-04-53](https://github.com/learningequality/kolibri-design-system/assets/13509191/b0b245c3-606b-4387-b2f6-4fd4e970de41)

needs to say "...from the `main` branch at https://main--kolibri-design-system.netlify.app/"

**Comment by MisRob** [comment]
> and also, has a broken link addressing the same on https://develop--kolibri-design-system.netlify.app/

This will be fixed by the above update in the README since we won't visit `develop--` build anymore. I assume it will stay live though because I believe Netlify keeps all previous builds alive. That's not a problem.

**Comment by BabyElias** [comment]
Okayy, working on this change.
Thank you for the insights :)

**Comment by MisRob** [comment]
Ah okay, that's great, thanks! I will assign you then.

**Comment by BabyElias** [comment]
Created PR #482 for the issue :)

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri-design-system/pull/482
