### ISSUE TITLE
Remove `setTimeout` from `useKWindowDimensions` and `useKResponsiveWindow` test files

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri-design-system#480]
- Remove `setTimeout` from `useKWindowDimensions` and `useKResponsiveWindow` test files (introduced [here](https://github.com/learningequality/kolibri-design-system/pull/469/files#diff-bcea926d00c2642a9632e956f05aa62418f24609ea0955966e19a96ac79bd892) and [here](https://github.com/learningequality/kolibri-design-system/pull/469/files#diff-7a645a2495ac5c8fc90fd5ad00a4f78cefbf3eecb01dd39d107a5718c33b88f1))
- Keep the tests but use a more reliable timing technique instead of using `setTimeout` which may cause the following problems:
  > flagging that using setTimeout in these tests like this could make them flaky - there's no guarantee that the content of the setTimeout will execute before the test itself is torn down, or that failures will even be registered (by @rtibbles)

**Comment by MisRob** [comment]
@rtibbles suggests using `$nextTick`

**Comment by Soren568** [comment]
Hi, I would like to work on this. Could you assign it to me?

**Comment by MisRob** [comment]
Hi @Soren568, yes, thank you!

**Comment by Soren568** [comment]
@MisRob I initiated the PR above, this is my first PR for kolibri so please let me know if there is anything I missed.

**Comment by MisRob** [comment]
Thank you, @Soren568

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri-design-system/pull/491
