### ISSUE TITLE
Remove 3rd party GH action from the changelog workflow

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri-design-system#481]
## Summary

In our GitHub Action to check that [CHANGELOG.md](https://github.com/learningequality/kolibri-design-system/blob/main/CHANGELOG.md) file contains some updates on each pull request

![Screenshot from 2023-10-26 16-18-13](https://github.com/learningequality/kolibri-design-system/assets/13509191/d7de95cb-7252-4506-a8b5-7d2397624e27)

https://github.com/learningequality/kolibri-design-system/blob/13e539592fd87508cd32f60e4ad22c1ec320559b/.github/workflows/changelog.yml#L1-L23

we use the third party package https://github.com/ankitjain28may/list-files-in-pr

https://github.com/learningequality/kolibri-design-system/blob/13e539592fd87508cd32f60e4ad22c1ec320559b/.github/workflows/changelog.yml#L12

which lists all files in a pull request.

This step needs to be replaced by our own implementation

## Value add

This is aligned with our overall strategy of using only official 3rd party GitHub actions to prevent from potential security or upgrade issues

## Acceptance criteria

- [ ] The changelog check on pull requests still works (that is, it fails when CHANGELOG.md file is not present in changed files of a pull requests, and passes otherwise)
- [ ] The action doesn't contain any unofficial 3rd party actions
- [ ] The custom implementation can be based on https://github.com/ankitjain28may/list-files-in-pr, however in that case it would include only logic that we use actively

**Comment by BabyElias** [comment]
Hello @MisRob ! Can I work on this issue?

**Comment by MisRob** [comment]
Hello @BabyElias, yes, thank you

**Comment by BabyElias** [comment]
Hey @MisRob ! 
Just to update, I am still working on this issue and will create a PR within 2-3 days.
Thank you so much for your patience :)

**Comment by MisRob** [comment]
Hi @BabyElias, thanks for the update. Take all the time you need.

**Comment by MisRob** [comment]
Great, thanks @BabyElias

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri-design-system/pull/505
