### ISSUE TITLE
Finish vendoring packages

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri-design-system#495]
**NOTE: This is obsolete, will update soon**

In KDS we use several 3rd party packages. At some point, we decided to vendor some of them, however this work is halfway through. To ensure smooth custom future updates of files we already vendored several years ago, we'd like to finish vendoring their dependencies to. This will also help with dependencies management.

## Goal

The following dependencies need to be removed from `package.json`'s `dependencies` and instead vendored to our codebase, namely to a new `/vendor` directory.

- [autosize](https://github.com/search?q=repo%3Alearningequality%2Fkolibri-design-system+autosize&type=code)
- [fuzzysearch](https://github.com/search?q=repo%3Alearningequality%2Fkolibri-design-system+fuzzysearch&type=code)
- [tippy.js](https://github.com/search?q=repo%3Alearningequality%2Fkolibri-design-system+tippy.js&type=code)
- [keen-ui](https://github.com/search?q=repo%3Alearningequality%2Fkolibri-design-system+keen-ui&type=code)
- [popper.js](https://github.com/search?q=repo%3Alearningequality%2Fkolibri-design-system+popper.js&type=code)
- [tippy.js](https://github.com/search?q=repo%3Alearningequality%2Fkolibri-design-system+tippy.js&type=code)

Also, all contents of `lib/keen` should be moved to `/vendor/keen` so that all vendored files are under one `vendor` directory.

## Acceptance criteria

- [ ] There is a new folder `/vendor`
- [ ] `/lib/keen` is moved to `/vendor/keen`
- [ ] Code of the packages referenced above is placed to `/vendor/<package_name>`
- [ ] Package code version should be the same as the version pinned in our package.json. (e.g. use https://github.com/atomiks/tippyjs/releases/tag/v4.2.1 to vendor `tippy.js` )
- [ ] All related imports are updated in the whole KDS codebase (e.g. `import fuzzysearch from 'fuzzysearch';` is replaced by `import fuzzysearch from '../vendor/fuzzysearch';`)
- [ ] Affected KDS places (e.g. a component, a mixin) is tested and confirmed that logic related to newly vendored package still works as expected

## Guidance

This is not required, however I'd recommend having one pull request for one package.

## Notes

Because of moving `/lib/keen` to `/vendor/keen` this will be a breaking change in Kolibri which sometimes imports vendored files directly, for example `import UiAlert from 'kolibri-design-system/keen/UiAlert';`.

However, after https://github.com/learningequality/kolibri/issues/11561 gets resolved, migration in Kolibri will be a matter of updating a few imports in its `apiSpec.js` file.

**Comment by MisRob** [comment]
@thanksameeelian dependabot PRs corresponding to the packages listed in the description can be closed

**Comment by nucleogenesis** [comment]
I was a bit concerned about what this would result in our needing to vendor. I made a new directory with this:

```
{
  "name": "deps",
  "dependencies": {
    "autosize": "^3.0.21",
    "fuzzysearch": "^1.0.3",
    "tippy.js": "^4.2.1",
    "keen-ui": "^1.3.0",
    "popper.js": "^1.14.6"
  }
}
```

Then `ls node_modules` shows the following (order changed to show the additional dependencies at the top):

```
lodash.debounce/
deepmerge/

autosize/
fuzzysearch/
keen-ui/
popper.js/
tippy.js/
```

So it seems like it won't be so big anyway.

**Comment by nucleogenesis** [comment]
One thought is that perhaps we should be putting our `vendor` directory in the root rather than the `lib` directory. My thinking is that we probably really shouldn't be exposing our dependencies directly to the users of KDS but rather should be exposing our own K-components that wrap the dependencies wherever they might be needed in products.

I do think that much of the uses of vendored stuff in Kolibri is due to how KDS was used before it ever became KDS where keen was a dependency of Kolibri and it made more sense to import from it. So long as Kolibri and KDS are separate I think it'd be better to discourage/disallow importing from KDS' new `vendor` directory.

[Related comment on #11561](https://github.com/learningequality/kolibri/issues/11561#issuecomment-1830949608)

**Comment by MisRob** [comment]
> One thought is that perhaps we should be putting our vendor directory in the root rather than the lib directory

Ah yes, that's a good point. I will update acceptance criteria accordingly.

**Comment by MisRob** [comment]
@nucleogenesis

>  So long as Kolibri and KDS are separate I think it'd be better to discourage/disallow importing from KDS' new vendor directory

Even if they would end up in a monorepo, I'd be good to continue having the clear line and only use what's public in products (there could be exceptions, but not as pattern)

**Comment by MisRob** [comment]
@nucleogenesis 

> Then ls node_modules shows the following (order changed to show the additional dependencies at the top):

Thanks for looking into it! Good news.

**Comment by rtibbles** [comment]
I am not sure why we would want to do this. We vendored keen specifically, but that's no reason to vendor other depencies and take on the maintenance burden of those packages as well.

**Comment by MisRob** [comment]
Closing this as we agreed that we won't be vendoring 3rd parties and rather freeze them if needed in package.json or vendor only if absolutely needed.

There's one unused dependency, `keen-ui`, that I will remove soon.
