### ISSUE TITLE
KModal does not shrink when the content has a smaller height

### ISSUE THREAD

**Issue by AlexVelezLl** [learningequality/kolibri-design-system#570]
## Product
Studio

## Expected behavior

The height of the KModal should dynamically adjust to the height of the content it renders.

## Actual behavior

If for some reason the content of the KModal is expanded after its first render, the KModal is expanded accordingly, but if it is then shrinked, the KModal remains with the height of the expanded content, and this can lead to cases like this:

If initially we have a componente with a description like this: 

![image](https://github.com/learningequality/kolibri-design-system/assets/51239030/ffb5421c-2211-46b2-9288-f83bee0833c7)

But then we want to delete it, we get this view: 

![image](https://github.com/learningequality/kolibri-design-system/assets/51239030/b9ad3ef4-35d0-4f82-80c3-de359994fa5a)

Cases like this occur in several places where the height of some element varies while the modal is displayed.

## Steps to reproduce the issue
1. Go to Studio and checkout the branch `studio-usability-enhancements`
2. Edit the content nodes of a channel
3. Edit the title and description of a node

## Environment
- OS: Ubuntu
- Browser version: Chrome Version 122.0.6261.94 (Official Build) (64-bit)

**Comment by shrudge** [comment]
hey @AlexVelezLl great notice, but I think you listed this issue in the wrong Repo, correct me if am i wrong tho, I am really new to open source so..

**Comment by AlexVelezLl** [comment]
Hi @shrudge! No, the issue is in the correct repository. KDS is responsible for providing the components that will be used in other Kolibri products, you can learn more about KDS in the [repo readme](https://github.com/learningequality/kolibri-design-system?tab=readme-ov-file#what-is-kolibri-design-system).

The issue is about the [KModal component](https://github.com/learningequality/kolibri-design-system/blob/d653942b300b48f60fef37783e84c8f6057c1a61/lib/KModal.vue), here in KDS, probably it has something to do with the [updateContentSectionStyle](https://github.com/learningequality/kolibri-design-system/blob/d653942b300b48f60fef37783e84c8f6057c1a61/lib/KModal.vue#L285) method.

**Comment by galovdev** [comment]
@AlexVelezLl Can I get this issue assigned?

**Comment by AlexVelezLl** [comment]
Hi @galovdev! Sure! Let me know if you have any question :)

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri-design-system/pull/590
