### ISSUE TITLE
KTextbox: Support a "clearable" prop to show a clear button

### ISSUE THREAD

**Issue by AlexVelezLl** [learningequality/kolibri-design-system#584]
## Product

For now in Studio to achieve some specs for the Studio Usability Enhancements project.

## Desired behavior

Add a "clear" button in the KTextbox component that only appears if there is non-empty text. When the user presses the clear button, the text should be deleted.

![image](https://github.com/learningequality/kolibri-design-system/assets/51239030/8e570c36-6968-4a6a-9ca7-68cbf7cbcb71)

Vuetify currently supports this using a `clearable` prop on its `VTextField`, so we can replicate this prop name.

## The Value Add

We give the user an option to easily delete all the text they have written.

**Comment by practicatto** [comment]
Hi! I'm new to this project and eager to start contributing. I've been looking for first issues and came across this issue. I believe I can provide the needed assistance to help solve it. Would it be possible for me to be assigned to this issue? :)

**Comment by ozer550** [comment]
> Hi! I'm new to this project and eager to start contributing. I've been looking for first issues and came across this issue. I believe I can provide the needed assistance to help solve it. Would it be possible for me to be assigned to this issue? :)

Hi @practicatto! Welcome and thanks for volunteering for this issue, I will assign this to you! feel free to reach out for any help while working with the issue.

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri-design-system/pull/591
