### ISSUE TITLE
Add upward icon opposite `dropdown`

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri-design-system#594]
## Product

Studio

## Desired behavior

Add the upward version of `dropdown` as `dropup` or `upward` or some other name. Also, since this icon is fairly generic, it may make sense to also add the left and right icons for comprehensivity.

## Current behavior

No such icon exists, and the chevron icons produce a completely different feel.

## (Optional) The Value Add

Studio uses it in opposing contexts of the existing `dropdown` icon.

## (Optional) Possible Tradeoffs

An alternative approach could be to simply use CSS to rotate the icon, but it would help to have that integrated into `KIcon` if the case. Although, there may be accessibility concerns in using CSS rotations on it.

**Comment by MisRob** [comment]
Documentation on adding a new icon https://github.com/learningequality/kolibri-design-system/blob/release-v4/dev_docs/05_icons.md#how-to-add-a-new-icon.

TODO @MisRob: Provide SVG file

**Comment by satyamkale27** [comment]
@MisRob I want to work on this issue please assign it to me.

**Comment by MisRob** [comment]
Hello @satyamkale27, thank you. I need to get the icon file from our design team at first. I will assign you as soon as I upload the file here.

**Comment by bjester** [comment]
SVG can be obtained here https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Aarrow_drop_up%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024

**Comment by satyamkale27** [comment]
@MisRob should i start working on it.

**Comment by MisRob** [comment]
I will assign you, @satyamkale27

**Comment by satyamkale27** [comment]
@MisRob i am begineer in vue js i am learning while contributing  please will you guide me in this 
(An alternative approach could be to simply use CSS to rotate the icon, but it would help to have that integrated into KIcon if the case. Although, there may be accessibility concerns in using CSS rotations on it.)

**Comment by MisRob** [comment]
Thank you, @satyamkale27, we will have a look

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri-design-system/pull/605
