### ISSUE TITLE
Make KTooltip's width configurable 

### ISSUE THREAD

**Issue by BabyElias** [learningequality/kolibri-design-system#595]
🌱 **Are you new to the codebase? Welcome and please see [the contributing guidelines](https://github.com/learningequality/kolibri-design-system/blob/release-v4/CONTRIBUTING.md).**

## Desired behavior

`KTooltip`'s maximum width can be configured, ideally via standard CSS `max-width`:

```
<KIcon ref="icon" icon="info" />
<KTooltip
  :style="{ 'max-width': '100px' }"
  reference="icon"
  :refs="$refs"
>
  Tooltip text tooltip text tooltip text tooltip text tooltip text
</KTooltip>
```

or alternatively (2) via a new `maxWidth` property

```
<KIcon ref="icon" icon="info" />
<KTooltip
  :maxWidth="100px"
  reference="icon"
  :refs="$refs"
>
  Tooltip text tooltip text tooltip text tooltip text tooltip text
</KTooltip>
```

where (1) is preferred and (2) acceptable (if (1) it's too much of struggle due to the use of the 3rd party library under the `KTooltip`'s hood)

Note that setting maximum width needs to be optional. `KTooltip` should maintain its current behavior of adjusting its size to fit its content if maximum width is not set.

## Current behavior

Setting max width

```
<KIcon ref="icon" icon="info" />
<KTooltip
  :style="{ 'max-width': '100px' }"
  reference="icon"
  :refs="$refs"
>
  Tooltip text tooltip text tooltip text tooltip text tooltip text
</KTooltip>
```

has no effect

![Screenshot from 2024-04-06 07-02-05](https://github.com/learningequality/kolibri-design-system/assets/13509191/107299f2-0bc6-41a4-926f-2180ce4201ef)

## Steps to reproduce

Run KDS development server and paste the code snippets from above to [the playground page](https://github.com/learningequality/kolibri-design-system/blob/release-v4/dev_docs/03_how_to_update_library.md#1-preview-updates-in-the-kolibri-design-system-environment).

## Impact

This is blocking migrating from Vuetify to KDS in [Studio](https://github.com/learningequality/studio) in some places where we need to be able to configure the maximum width, for example in [HelpTooltip.vue](https://github.com/learningequality/studio/blob/9ed0725411d013a9c08688e601a2083893f7fdfe/contentcuration/contentcuration/frontend/shared/views/HelpTooltip.vue).

| Vuetify | KDS |
| -------- | ------- |
| ![Screenshot from 2024-04-06 07-07-41](https://github.com/learningequality/kolibri-design-system/assets/13509191/5e28d9c3-5aa1-4dc6-a1c4-e4ad595777a1) | ![image](https://github.com/learningequality/kolibri-design-system/assets/95405559/35ac37bd-eb75-4266-8cd8-0449c47a315f) |

## Trade-offs

Not aware of any.

## Acceptance criteria

- [ ] There are no regressions in existing `KTooltip`'s, such as those in [Kolibri](https://github.com/learningequality/kolibri) (see ["Preview updates in a product"](https://github.com/learningequality/kolibri-design-system/blob/release-v4/dev_docs/03_how_to_update_library.md#2-preview-updates-in-a-product) to find out how to check on this)

**Comment by MisRob** [comment]
I moved this outside the issue since it will need to be decided, but pasting @BabyElias's comment here as guidance that could be helpful:

> Adding a maxWidth attribute or setting the width as 100% can help prevent viewport overflow for KTooltip Content. This was discussed earlier on Slack [here](https://learningequality.slack.com/archives/C03S2EN192A/p1710849266286059?thread_ts=1710822485.715359&cid=C03S2EN192A) with reference to [Issue #4451](https://github.com/learningequality/studio/issues/4451) in Studio.

**Comment by MisRob** [comment]
@BabyElias I finalized the issue

**Comment by MisRob** [comment]
Thank you for reporting, @BabyElias. I rewrote the issue to make clear what are the expectations.

**Comment by satyamkale27** [comment]
@MisRob I want to work on this issue please assign it to me.

**Comment by MisRob** [comment]
Thanks @satyamkale27, I will assign you

**Comment by MisRob** [comment]
@satyamkale27 Please target `release-v3` branch

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri-design-system/pull/611
