### ISSUE TITLE
Add examples to KTextbox documentation

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri-design-system#596]
## Overview

@GarvitSinghal47 pointed out that some of our components' docs could be improved with some examples, starting with KTextbox.

Not all variations need to be applied, however, a handful of the props' examples would be a great improvement.

## Acceptance criteria

The following examples can be made initially and further updates to component docs can be discussed afterward:

- [ ] `invalid` and `invalidText` -- this will need to have a note to the user regarding what is and isn't valid so that they can test it out
- [ ] `disabled` 
- [ ] `number` `min` `max` 
- [ ] `textarea`
- [ ] `label` 

---

I think that going beyond 5 examples might ultimately make the page less usable/readable overall but once these are in place we can discuss further.

**Comment by GarvitSinghal47** [comment]
@nucleogenesis feel free to assign me this issue.
