### ISSUE TITLE
Improve overflow handling in KTabsList component

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri-design-system#623]
🌱 **Are you new to the codebase? Welcome and please see [the contributing guidelines](https://github.com/learningequality/kolibri-design-system/blob/release-v4/CONTRIBUTING.md).**

## Desired behavior

- [`KTabsList`](https://design-system.learningequality.org/ktabslist/), and therefore also [`KTabs`](https://design-system.learningequality.org/ktabs/) (which is built on top of it)
 
![Screenshot from 2024-04-19 12-23-59](https://github.com/learningequality/kolibri-design-system/assets/13509191/d1e39ec6-4dff-4d20-b167-9e47ca980dbc)

should always take up one row. If the tab list items can't fit into one row, the items for which there is not enough space should collapse into a dropdown menu, such as

![Screenshot from 2024-04-19 11-51-43](https://github.com/learningequality/kolibri-design-system/assets/13509191/a2d5cc49-bbab-4cd6-8610-438ddc051333)

- `KTabsList` should utilize [`KListWithOverflow`](https://design-system.learningequality.org/klistwithoverflow/) under the hood to achieve this behavior. See the "Guidance" section below for more information.

- This should be the default behavior of both `KTabsList` and `KTabs`.

## Current behavior

When there is not enough space, `KTabsList`'s items wrap into more rows:

![Screenshot from 2024-04-19 11-52-53](https://github.com/learningequality/kolibri-design-system/assets/13509191/96c8894b-b3f7-488c-b679-5f4e554626f4)

## Steps to reproduce

Run the KDS development server and paste the following into [the playground page](https://github.com/learningequality/kolibri-design-system/blob/release-v4/dev_docs/03_how_to_update_library.md#1-preview-updates-in-the-kolibri-design-system-environment):

```vue
<template>

  <div>
    <KTabsList
      v-model="activeTabId"
      tabsId="tabs-1"
      ariaLabel="Coach reports"
      :tabs="tabs"
    />
    <KTabsPanel
      tabsId="tabs-1"
      :activeTabId="activeTabId"
    />
  </div>

</template>


<script>
  export default {
    data() {
      return {
        tabs: [
          { id: 'tabLessons', label: 'Lessons' },
          { id: 'tabLearners', label: 'Learners' },
          { id: 'tabGroups', label: 'Groups' },
        ],
        activeTabId: 'tabLessons',
      };
    },
  };

</script>
```

## Impact

- Provides a much better experience. Tab list items spanning two or more rows can be disorienting.
- Improves all current and future places in Kolibri where we use `KTabsList`.
- Will resolve https://github.com/learningequality/kolibri/issues/12011 (after `TabsWithOverflow` is updated to not contain custom overflow logic)

## Trade-offs

Not aware of any.

## Guidance

- `KTabsList` should use `KListWithOverflow` by default, as there are no cases where we want a different behavior in a tabs list.
- Guidance from @AlexVelezLl - basically, this can likely be handled with an approach similar to:

```vue
// KTabsList.vue

<KListWithOverflow
  :items="tabs"
  ...
>
  <template #item="{ item }">
    <router-link v-if="useRouter" ...>
      ...
    </router-link>
    <button v-else .../>
  </template>
  ...
</KListWithOverflow>
```

- `KListWithOverflow` and `KTabsList` were developed independently and they both may need some adjustments to work together well

## Acceptance criteria

- [ ] `KListWithOverflow` is used to achieve the desired behavior
- [ ] There are no regressions in `KListWithOverflow`
- [ ] There are no regressions in `KTabsList` and `KTabs` behavior, such as keyboard navigation and focus ring. All documentation live examples as well as places in Kolibri where we use them work as before. 
- [ ] There is a11y QA (@radinamatic) to confirm that `KTabsList` and `KListWithOverflow` together provide a good a11y experience as a whole

**Comment by MisRob** [comment]
Closing since another approach will be implemented to handle overflow in tabs. See https://github.com/learningequality/kolibri/pull/12146#issuecomment-2127951322
