### ISSUE TITLE
Update the favicon in the KDS to reflect the new brand logo

### ISSUE THREAD

**Issue by AllanOXDi** [learningequality/kolibri-design-system#641]
Instructions:
- update the favicon displayed in browser tabs to the new  brand logo. 
## Product
KDS

**Comment by RONAK-AI647** [comment]
Hey @AlexVelezLl , I am interested in resolving this issue, I will be happy if u assign it to me, Thank you.

**Comment by rtibbles** [comment]
Hi @RONAK-AI647 - I have assigned you! To avoid having to reinvent the wheel, please find the favicon that we use in Kolibri here: https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/default_theme/static/assets/default_theme/logo.ico - you should be able to just copy this for use to resolve this issue!

**Comment by RONAK-AI647** [comment]
Hey @AlexVelezLl @rtibbles  ,I have raised a PR ,kindly review and let me know your comments.

**Comment by rtibbles** [comment]
Thanks, we'll take a look!

**Comment by rtibbles** [comment]
Fixed in #809
