### ISSUE TITLE
Remove Internet Explorer 11 specific logic from KTextTruncator

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri-design-system#643]
🌱 **Are you new to the codebase? Welcome and please see [the contributing guidelines](https://github.com/learningequality/kolibri-design-system/blob/develop/CONTRIBUTING.md).**

## Description

Remove logic specific to Internet Explorer 11 from `KTextTruncator`, including:
- The [`lineHeightIE` prop](https://github.com/learningequality/kolibri-design-system/blob/3200a8711d031752665db2bc29e96f9e388a9d05/lib/KTextTruncator.vue#L63)
- The IE11 fallback [from the `truncate` method](https://github.com/learningequality/kolibri-design-system/blob/3200a8711d031752665db2bc29e96f9e388a9d05/lib/KTextTruncator.vue#L105-L142)
- Other related cleanup if identified

## Impact

Starting with Kolibri 0.17, we're dropping IE11 support. Therefore, KDS no longer needs to account for IE11-specific cases. This update removes unnecessary code, making future maintenance easier.

## Trade-offs

None identified.

## Guidance

Target the `develop` branch, as this will be released as a breaking change.

## Acceptance criteria

- [ ] The updated `KTextTruncator` [is tested, for example in Kolibri](https://github.com/learningequality/kolibri-design-system/blob/develop/dev_docs/03_how_to_update_library.md#2-preview-updates-in-a-product), and has no regressions

**Comment by Nivas7** [comment]
Can you Assign me on this issue?

**Comment by Nivas7** [comment]
Can you please Assign me on this issue?

**Comment by MisRob** [comment]
Hi @Nivas7, yes, thanks for volunteering!

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri-design-system/pull/652
