### ISSUE TITLE
Replace the "Changelog" link with the "Release notes" link on the KDS documentation website

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri-design-system#644]
🌱 **Are you new to the codebase? Welcome and please see [the contributing guidelines](https://github.com/learningequality/kolibri-design-system/blob/develop/CONTRIBUTING.md).**

## Description

Replace the "Changelog" link with the "Release notes" link on the KDS documentation website. Use this link as the target: https://github.com/learningequality/kolibri-design-system/releases.

![changelog](https://github.com/learningequality/kolibri-design-system/assets/13509191/e178c898-b4d8-4360-b262-3a58a9e3ff9a)

## Impact

Since we've started preparing "Release notes", it is more relevant to direct developers to them rather than to the changelog.

## Trade-offs

None identified.

## Guidance

Target the pull request to the default `release-v*` branch.

## Acceptance criteria

- [ ] The link functions correctly in both the local environment and the production build

**Comment by musser004** [comment]
Hi there,

Hope everything's going well on your end! New contributor here and since this looks extremely straightforward, could I request to be assigned this one?

**Comment by MisRob** [comment]
Welcome @musser004 and thank you for volunteering. I will assign you.

**Comment by musser004** [comment]
Thanks! Just put through the pull request for this one. I think everything's good with the change, I may just need to reformat the pull request message itself a little bit. Anyways, have a great weekend!

#653

**Comment by MisRob** [comment]
Thank you @musser004, we appreciate it and review it.

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri-design-system/pull/653
