### ISSUE TITLE
KSelect: Add documentation about the new events and slots

### ISSUE THREAD

**Issue by AlexVelezLl** [learningequality/kolibri-design-system#664]
🌱 **Are you new to the codebase? Welcome and please see [the contributing guidelines](https://github.com/learningequality/kolibri-design-system/blob/develop/CONTRIBUTING.md).**

## Summary

Document all props, slots, events, and public methods of KSelect that [are not documented yet](https://design-system.learningequality.org/kselect/#props).

![kselect](https://github.com/learningequality/kolibri-design-system/assets/13509191/d9c9f843-a96c-4456-9a17-79a0610cc87f)

## Context

In #549 we introduced an important refactor of KSelect as part of moving away from `KeenUiSelect` vendored component, and as a result we ended up having all the events, slots and public methods exposed by `KeenUiSelect` in `KSelect`, and the most of them doesn't have any description in our [docs](https://design-system.learningequality.org/kselect/).

## Desired behavior

Would be great to have this new API documented, so anyone that reads them can understand it.

## Guidance

Note that the props, slots, and events documentation is auto-generated from JSDoc strings in the Vue component - so that's the right place where to document it all. See https://github.com/learningequality/kolibri-design-system/blob/release-v4/dev_docs/04_how_to_update_docs.md#updating-the-library-components-documentation.

**Comment by yeshwanth235** [comment]
Hi @AlexVelezLl, 
Please assign this issue to my name

**Comment by ozer550** [comment]
Thanks for volunteering on this @yeshwanth235! assigning this to you.

**Comment by yeshwanth235** [comment]
Please review. If everything looks good, I'll raise the PR.

**Props**
![Image](https://github.com/user-attachments/assets/45fd7b33-48c9-4525-99ac-722682144d79)
**Events**
![Image](https://github.com/user-attachments/assets/8c4208bc-e02c-41dc-9844-ad24fb9d8ab3)
**Slots And Methods**
![Image](https://github.com/user-attachments/assets/c64b77d9-c8b7-4143-9435-6581bff1c0e1)

**Comment by yeshwanth235** [comment]
Is there a playground where we can use Kolibri components? If so, please share the link.

**Comment by AlexVelezLl** [comment]
Hey @yeshwanth235! Yes, this looks like the right change. Please raise a PR so we can have a better look.

> Is there a playground where we can use Kolibri components? If so, please share the link.

Yes! Here you can find our playground page: https://github.com/LearningEquality/Kolibri-Design-System/blob/develop/docs/pages/playground/index.vue. And you can see it rendered in `http://localhost:4000/playground`

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri-design-system/pull/821
