### ISSUE TITLE
[Visual Testing]: Implement visual tests of KButton

### ISSUE THREAD

**Issue by AlexVelezLl** [learningequality/kolibri-design-system#689]
## Product
KDS.

## Desired behavior

After #685, we ended up with a very straightforward way of writting visual tests. Now lets implement exhaustive tests for one component - KButton, and test the whole visual tests process with this component.

We should take the snapshot of the different visual combinations of KButton:
- KButton as primary raised button
- KButton as primary flat button
- KButton as secondary raised button
- KButton as secondary flat button
- KButton as basic link
- KButton as raised button disabled
- KButton as flat button disabled
- KButton as raised button with hover state
- KButton as flat button with hover state
- KButton with icon and afterIcon
- KButton with default slot

## Current behavior
Currently we just have the basic example with default props.

**Comment by KshitijThareja** [comment]
Hi @AlexVelezLl 
Thanks for creating the issue. I'll try to create a PR for this soon :)

**Comment by AlexVelezLl** [comment]
Thank you @KshitijThareja!

**Comment by AlexVelezLl** [comment]
Closed by #710.
