### ISSUE TITLE
Add documentation to the KTooltip page

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri-design-system#694]
🌱 **Are you new to the codebase? Welcome! Please see [the contributing guidelines](https://github.com/learningequality/kolibri-design-system/blob/develop/CONTRIBUTING.md).**

## Summary

The [`KTooltip` documentation page](https://design-system.learningequality.org/ktooltip/) lacks an overview and examples of usage. The goal of this issue is to:

- [ ]  Add the “Overview” section with a brief introduction on what the component is for.
- [ ]  Add the “Usage” section with sub-sections documenting:
    - [ ]  The basic usage with an example code snippet and the visualization of its output. The example should include `reference` and `refs` explanation and show how `KTooltip` is used together with another component, such as `KIcon` ([Kolibri codebase examples](https://github.com/search?q=repo%3Alearningequality%2Fkolibri%20%3CKTooltip&type=code)).
    - [ ]  A visualization of the `disabled` state
    - [ ]  A visualization of all supported `placement`s
    - [ ]  A visualization of `maxWidth`

## Guidance

- For consistency in documentation, first see the [“Writing” guidelines](https://design-system.learningequality.org/writing/) and use existing pages for reference, such as the [`KTextbox`](https://design-system.learningequality.org/ktooltip/) [documentation](https://design-system.learningequality.org/ktextbox/) and [`KImg` documentation](https://design-system.learningequality.org/kimg/) pages.
- Generally we try to strike a balance between documenting all important modes of a component, while not overwhelming readers with unnecessary details or exhaustive lists of all possible states.
- Use simple, clear, and concise language. Think about whether what you are explaining can be easily understood by newcomers.
- To understand the technical aspects of writing documentation, refer to:
    - [“How to update the documentation website”](https://github.com/learningequality/kolibri-design-system/blob/release-v4/dev_docs/04_how_to_update_docs.md)
    - Documentation pages code, such as [`KTextbox` docs source code](https://github.com/learningequality/kolibri-design-system/blob/9d2a147de7e81c945ca0eab7ffb2c4719fd2bb06/docs/pages/ktextbox.vue) or [`KImg`'s docs source code](https://github.com/learningequality/kolibri-design-system/blob/9d2a147de7e81c945ca0eab7ffb2c4719fd2bb06/docs/pages/kimg.vue)

**Comment by sruthin21** [comment]
I want to work on this Issue Please Assign This to me

**Comment by AlexVelezLl** [comment]
Thanks for your interest in picking this up @sruthin21!! I just assigned this issue to you :hugs:. Please let us know if there is anything we can help with :open_hands:.

**Comment by sruthin21** [comment]
sure @AlexVelezLl  Thanks for assigning

**Comment by MisRob** [comment]
Work and review in https://github.com/learningequality/kolibri-design-system/pull/789 can serve as a good guidance since that PR nearly finished the issue.

**Comment by shruti862** [comment]
I want to work on this issue .Can you please assign this to me.

**Comment by MisRob** [comment]
Hi @shruti862, sure, thanks! Please read carefully the guidance, comments, and the referenced pull request - you can find all you need there to finish this successfully.

**Comment by shruti862** [comment]
@MisRob Thank you for assigning the issue ; I have gone through the referenced PR soon I will raise PR.

**Comment by shruti862** [comment]
@MisRob Can you please also review this PR ( whenever you get time ) to see if there any more changes needed.

**Comment by MisRob** [comment]
Yes, @shruti862, I've just posted a comment there. Thank you.

**Comment by shruti862** [comment]
@MisRob I did yarn lint-fix for linting issue in the new PR which only contains ktooltip file changes as you suggested ; please review it whenever you get time.

**Comment by MisRob** [comment]
Thanks @shruti862

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri-design-system/pull/859
