### ISSUE TITLE
KCard: Add prop validators for 'layout' and 'thumbnailDisplay'

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri-design-system#695]
## Summary

This is one of the follow-ups to https://github.com/learningequality/kolibri-design-system/pull/625

1. Use constants for all allowed `layout` and `thumbnailDisplay` prop values
2. Add custom prop validators for these two props so that `KCard` throws an error when an invalid value is passed.

### Guidance

You can see an example in `KImg`:

https://github.com/learningequality/kolibri-design-system/blob/6a6865f1060e1da160b77b7b851f82f340f453a1/lib/KImg/index.vue#L56-L60

https://github.com/learningequality/kolibri-design-system/blob/6a6865f1060e1da160b77b7b851f82f340f453a1/lib/KImg/index.vue#L56-L60

https://github.com/learningequality/kolibri-design-system/blob/6a6865f1060e1da160b77b7b851f82f340f453a1/lib/KImg/index.vue#L124-L132

**Comment by AllanOXDi** [comment]
completed in https://github.com/learningequality/kolibri-design-system/pull/707
