### ISSUE TITLE
KCard: Complete vertical/horizontal layouts with no thumbnail 

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri-design-system#699]
## Summary

This is one of the follow-ups to https://github.com/learningequality/kolibri-design-system/pull/625

Check that `KCard` supports vertical/horizontal layouts with no thumbnail well and add some examples to the documentation page.

This is to ensure that it can support cards like

![Screenshot from 2024-07-26 21-30-16](https://github.com/user-attachments/assets/407bc6c0-033b-48b6-a480-159b93ab79a9)

## Guidance

- Try if cards like above can be easily achieved by the current `KCard` or if we need to add some internal code or new interface APIs to be able to do so
- I think there's no need to distinguish between `'vertical'` and `'horizontal'` layout in this case when `'thumbnailDisplay'` is `'none'`. So the expected behavior would be that any time `thumbnailDisplay='none'`,  `KCard`'s output would be such as illustrated on the designs.

## References

[Figma](https://www.figma.com/design/1tQQ0Sw1yDjzO66hyjLVPM/Kolibri-UX-Fixes?node-id=1097-30500)

**Comment by MisRob** [comment]
With @AllanOXDi we agreed to use the same approach for hiding the slot areas when empty as in https://github.com/learningequality/kolibri-design-system/issues/702. That is, by adding `preserverFooter` and `preserveBelowTitle` props.

**Comment by MisRob** [comment]
Note that here we will preserve 24px spaces introduced here https://github.com/learningequality/kolibri-design-system/issues/704 (slightly different from the screenshot)

**Comment by AllanOXDi** [comment]
fix in  #699
