### ISSUE TITLE
KCard: Add an option to configure thumbnail alignment

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri-design-system#701]
## Summary

Add an option to configure the thumbnail area alignment via a new prop  `thumbnailAlign`.

## References

 This need is motivated by new additions to the cards family in Kolibri, such as
- https://github.com/learningequality/kolibri/issues/12318
- https://github.com/learningequality/kolibri/issues/12317
- https://github.com/learningequality/kolibri/issues/12319

## Current behavior

Currently, `KCard`  with `layout="horizontal"` and `thumbnailDisplay="large"` renders as

<img src="https://github.com/user-attachments/assets/2ae09dec-5a0e-4646-973d-d09418b4b185" width="400" />

and with `layout="horizontal"` and `thumbnailDisplay="small"` as

<img src="https://github.com/user-attachments/assets/e2088eb9-514d-4427-a92d-dfc99ad2ca0b" width="400" />

There is no `KCard` API yet that allows to configure whether the thumbnail area is displayed on the left side or the right side.

## Expected behavior

There is a new `thumbnailAlign` prop that accepts `'left'` and `'right'` values, and it decides on which side is the thumbnail area displayed, particularly in the layouts mentioned above.

All other layouts either don't have the thumbnail area or it takes the whole width of the card so they should simply ignore this prop. This would ideally be mentioned in the prop's JSDoc string.

## Acceptance criteria

- [x] Implemented as specified above
- [x] No regressions in any other layout
- [x] New prop has a custom validator and is documented
- [ ] Supports RTL

**Comment by AllanOXDi** [comment]
fixed in https://github.com/learningequality/kolibri-design-system/pull/706
