### ISSUE TITLE
KCard: Add an option to configure whether the "aboveTitle" slot with no content should occupy the area designated for it or not

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri-design-system#702]
## Summary

Consumers need to be able to choose whether the `aboveTitle` slot with no content should still occupy the area designated for it or not. This behavior can be configured via a new prop, `preserveAboveTitle`.

## References

 This need is motivated by new additions to the cards family in Kolibri, such as
- https://github.com/learningequality/kolibri/issues/12318
- https://github.com/learningequality/kolibri/issues/12317
- https://github.com/learningequality/kolibri/issues/12319

## Current behavior

When the `aboveTitle` slot has no content, `KCard` still reserves the space for in the same way as if there was content. The motivation behind this is to be able to achieve consistent alignment of title when there are more cards on the same grid row.

<img src="https://github.com/user-attachments/assets/6be186a8-bd32-4ff4-b3b9-57bb708e61d6" width="600" />

## Expected behavior

The behavior described above should still be achievable, however we have an option to configure it via a new Boolean prop, `preserveAboveTitle`.

If set to `true` and `aboveTitle` has no content, the slot's area should still occupy the space designated for it (current behavior).

If set to `false` and `aboveTitle` has no content, the slot's area should be completely removed. Also note that in this case, the space above the title needs to be `24px`.

 <img src="https://github.com/user-attachments/assets/874a08d2-54e1-463c-bf6d-2f11509c2139" width="300" />

Since in the first several production cards the slot is not preserved, let's set the default value to `false`.

## Acceptance criteria

- [x] Implemented as specified above
- [x] The new prop works for all layouts
- [x] The new prop is documented with JSDoc string
- [ ] There are a few unit tests for it
- [x] No regressions in any of the layouts
  - e.g. ensure that when `aboveTitle` has content, it should show no matter of `preserveAboveTitle` value

**Comment by AllanOXDi** [comment]
fixed in https://github.com/learningequality/kolibri-design-system/pull/705
