### ISSUE TITLE
Remove deprecated dropshadows

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri-design-system#725]
🌱 **Are you new to the codebase? Welcome! Please see [the contributing guidelines](https://github.com/learningequality/kolibri-design-system/blob/develop/CONTRIBUTING.md).**

## Blocked by

- https://github.com/learningequality/kolibri/issues/12552
- https://github.com/learningequality/kolibri-design-system/issues/724

## Summary

For both internal KDS components styling and external use by non-KDS components in our products, according to the updated guidelines [in the "Elevation and shadow > Drop shadows" documentation section](https://deploy-preview-723--kolibri-design-system.netlify.app/styling/#elevation), we only need to keep `%dropshadow-1dp` , `%dropshadow-2dp` , and `%dropshadow-6dp` in the *definitions.scss*:

[https://github.com/learningequality/kolibri-design-system/blob/0cbdf57d24690cb6c23618ba700118a831cd9ffc/lib/styles/definitions.scss#L59-L157](https://github.com/learningequality/kolibri-design-system/blob/0cbdf57d24690cb6c23618ba700118a831cd9ffc/lib/styles/definitions.scss#L59-L157)

All other `%dropshadow-...` should not be available for use.

## Guidance

- I think it’d be fine to just comment them out rather than delete, in case we need some of them in the future - as long as there’s a note that uncommenting needs to be discussed with designers and should be aligned with the guidelines. 
- Issues in "Blocked by" should be resolved first to ensure that KDS version upgrade is not demanding in Kolibri that has many drop shadows. Still needs to be communicated as a breaking change and  consumers should double-check before installing the corresponding release (the issues mentioned should cover most of it, however there may be one or two places in Studio to update as well)

**Comment by lokesh-sagi125** [comment]
i've already finished commenting the deprecated drop shadows , can you assign this to me, so i can PR my changes?

**Comment by MisRob** [comment]
Thanks @lokesh-sagi125. I'll assign you. Just a note it's better to get assigned first in case some clarification is needed, so please always message us and wait for assignment.

Would you mind splitting https://github.com/learningequality/kolibri-design-system/pull/734 into two pull requests? One that resolves https://github.com/learningequality/kolibri-design-system/issues/724 and another that resolves this issue.

These are deliberately two issues because https://github.com/learningequality/kolibri-design-system/issues/724 can be merged soon, whereas for the other one we will be waiting until https://github.com/learningequality/kolibri/issues/12552, otherwise it'd break many places in Kolibri. We will then review both pull requests.

**Comment by Rahul-web-hub** [comment]
Hi @MisRob , could you please assign this issue to me? I would like to work on it. Thanks!

**Comment by lokesh-sagi125** [comment]
hey @MisRob @AlexVelezLl  i am not sure why i was unassigned from this issue, if in case its because of my inactivity ,i was waiting for 
(https://github.com/learningequality/kolibri/issues/12552) as it blocks this issue, i have removed the deprecated dropshadows and will be raising a PR as long as this issue gets unblocked

**Comment by MisRob** [comment]
Sorry about that @lokesh-sagi125, that was an oversight on my side. I will re-assign you again. Feel free to open a PR and we will take care of merging it at the right time.

**Comment by MisRob** [comment]
Hi @Rahul-web-hub, I posted links to other issues here for you https://github.com/learningequality/kolibri/issues/12552#issuecomment-2413131138

**Comment by Rahul-web-hub** [comment]
> Hi [@Rahul-web-hub](https://github.com/Rahul-web-hub), I posted links to other issues here for you [learningequality/kolibri#12552 (comment)](https://github.com/learningequality/kolibri/issues/12552#issuecomment-2413131138)

no problem ,I would be more than happy to work on other issues

**Comment by MisRob** [comment]
Lovely thanks @Rahul-web-hub

**Comment by AlexVelezLl** [comment]
Hey @lokesh-sagi125. https://github.com/learningequality/kolibri/issues/12552 is about to be merged, you can open your PR for this issue now :)

**Comment by lokesh-sagi125** [comment]
thanks @AlexVelezLl  will do .

**Comment by lokesh-sagi125** [comment]
hey @AlexVelezLl  just raised a  [pr](https://github.com/learningequality/kolibri-design-system/pull/815)

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri-design-system/pull/815
