### ISSUE TITLE
KCard: Remove the border-radius on align left

### ISSUE THREAD

**Issue by AllanOXDi** [learningequality/kolibri-design-system#741]
🌱 **Are you new to the codebase? Welcome! Please see [the contributing guidelines](https://github.com/learningequality/kolibri-design-system/blob/develop/CONTRIBUTING.md).**

## Summary
We  need to remove  border-radius when the thumbnail display is align left using `thumbnailAlign` prop. But keep it when the the thumbnail  is align left  and   `thumbnailDisplay `prop is small
## References
This need is motivated by new additions to the cards family in Kolibri, such as

https://github.com/learningequality/kolibri/issues/12318
https://github.com/learningequality/kolibri/issues/12317
https://github.com/learningequality/kolibri/issues/12319
## Current behavior
When the card  is align left we are still seeing small rounded corners  around  the card's outer border.

 
<img width="642" alt="Screenshot 2024-08-21 at 17 57 04" src="https://github.com/user-attachments/assets/7fd4097a-59e1-4d60-98fe-ecd777223f28">

### Expected behavior
The border-radius  needs to be removed on `:thumbnailAlign='left`' and `:thumbnailDisplay='large'`

## Acceptance criteria

- [ ]  Implemented as specified above

**Comment by Spoorthy1423** [comment]
Hey!! I would like to work on this issue @AllanOXDi  please assign me this issue!!

**Comment by AllanOXDi** [comment]
Hi @Spoorthy1423 I have assigned it to you

**Comment by Spoorthy1423** [comment]
Can u please review my PR @AllanOXDi .

**Comment by Spoorthy1423** [comment]
Hey!! @AllanOXDi can u review my pr please!!! i would like to contribute to this repo further.

**Comment by AllanOXDi** [comment]
Hey @Spoorthy1423 Thanks for letting me know . I  have reviewed your PR and left for you  a small comments. But overall, the changes looks good to me. Thank you for working on this issue.

**Comment by Spoorthy1423** [comment]
Hey!! @AllanOXDi i will change all as soon as possible, a small request can u please merge this issue today itself as i have a deadline of submission in my academics..Thank you!

**Comment by Spoorthy1423** [comment]
Hey!! @MisRob i have raised another pr where i changed all the changes described and maintained changelog but in the last my pull request link is a bit wrong hope u get that in it..hope u like it Thank you!!

**Comment by MisRob** [comment]
Close by https://github.com/learningequality/kolibri-design-system/pull/754
