### ISSUE TITLE
Disconnection Screen Overlay looks like it has a lower z-index than the KModal

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri-design-system#75]
This was originally a problem in learningequality/kolibri#6301, and I'm wondering if something changed with the KModal in this library, because I'm seeing the KModal form appear over the disconnection overlay again. Fortunately, I can close the modal without seeing the same errors as in that issue.

<img width="1087" alt="CleanShot 2020-07-14 at 15 23 35@2x" src="https://user-images.githubusercontent.com/10248067/87482464-4c365300-c5e6-11ea-9bbf-5030780f7f8d.png">

**Comment by nucleogenesis** [comment]
Fixed in #7360
