### ISSUE TITLE
Make the KCard thumbnail handle large Card width

### ISSUE THREAD

**Issue by AllanOXDi** [learningequality/kolibri-design-system#773]
## Desired behavior
The thumbnail should maintain its height at all KCard widths.

## Current behavior
It appears that the larger the KCard when set to horizontal layout and thumbnailDisplay small,  the thumbnail  height goes past the KCard itself, thus overshadowing the footer section.

<img width="766" alt="Screenshot 2024-09-05 at 14 46 22" src="https://github.com/user-attachments/assets/132a5d5b-78b1-493f-b28c-889024bfbd77">

**Comment by MisRob** [comment]
Thanks for reporting @AllanOXDi :) I can't say for sure right now, but it's quite possible that this will be resolved by https://github.com/learningequality/kolibri-design-system/pull/748 - so when we start building actual features in Studio (that will need to happen with `KGrid`), let's see if it can still be reproduced.
