### ISSUE TITLE
Update KDS Theme Token values

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri-design-system#775]
When upgrading our themes for the rebrand, the new numerical token values for colors did not correspond exactly to the material specifications. This is fine in main Kolibri, but presents a challenge for upgrading custom themed Kolibri.

While we will need to make these changes in some places in Kolibri as well, the first thing will be to make the changes in KDS.

The updated mapping: 
![Screenshot 2024-09-06 at 12 14 29 PM](https://github.com/user-attachments/assets/6554cc04-50f1-4517-97b1-f5df682b65e7)

**Comment by AlexVelezLl** [comment]
Closed by #782
