### ISSUE TITLE
KIconButton: Set `tooltip` value as fallback if `ariaLabel` is missing

### ISSUE THREAD

**Issue by AlexVelezLl** [learningequality/kolibri-design-system#793]
🌱 Are you new to the codebase? Welcome! Please see [the contributing guidelines](https://github.com/learningequality/kolibri-design-system/blob/develop/CONTRIBUTING.md).

## Product
Kolibri, Studio, etc.

## Description

In `KIconButton` we have these two props related but not exactly the same: `ariaLabel` and `tooltip`.  For accessibility purposes we dont want these props to be the same, but if the user forgot to send an `ariaLabel` prop but they sent a `tooltip` prop, the ariaLabel should take the value of the `tooltip` prop.

This means, the aria label of the icon button will be set by the `ariaLabel` prop, and have the `tooltip` value as fallback if `ariaLabel` is missing.

## The Value Add
This will improve accessibility in places where we have tooltips but no aria labels. And in the future we can just send the `tooltip` prop if we want the `ariaLabel` to have the same value.

**Comment by shivam-daksh** [comment]
@AlexVelezLl , Could you assign this to me?

**Comment by MisRob** [comment]
Hi @shivam-daksh, thanks again. I will assign you this one alongside https://github.com/learningequality/kolibri-design-system/issues/795 so that you can switch tasks. Regarding other issues you volunteered for, let's leave it for later when these two are resolved.

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri-design-system/pull/798
