### ISSUE TITLE
[KTable]: Update Sorting Flow to Include "Unsorted" State

### ISSUE THREAD

**Issue by BabyElias** [learningequality/kolibri-design-system#797]
**🌱 Are you new to the codebase? Welcome! Please see [the contributing guidelines](https://github.com/learningequality/kolibri-design-system/blob/develop/CONTRIBUTING.md).**
## Summary
Currently, once a user clicks on a header to sort a column in KTable, the sorting flow cycles between unsorted > ascending > descending > ascending > descending, with no way to return to the default unsorted state without refreshing the page. This issue aims to update the sorting behavior to allow users to return to the unsorted/default state after any column header has been clicked.
## The Value Add 
Adds flexibility in how users can interact with the table, especially when sorting is not desired or needs to be reset.
## New Sorting Flow
The desired behavior after clicking a sortable column header should be:

- `unsorted > ascending > descending > unsorted > ascending > descending` and so on.
- This means that after a column has been sorted in first ascending, then descending order, clicking the header again should return it to the unsorted/default state before cycling back to ascending order.
## Guidance
- Implement an additional step in the sorting flow for resetting the column to the default unsorted state.
- **Note** : This is only for cases where `<KTable sortable>` is used i.e KTable with enabled default sorting, which makes use of the useSorting composable as referenced [here](https://github.com/learningequality/kolibri-design-system/blob/develop/lib/KTable/useSorting/index.js).

## Acceptance Criteria 

- [ ] Clicking a sortable header cycles through the new sorting order: unsorted > ascending > descending > unsorted > ....
- [ ] Unit tests are added or updated to verify the new sorting flow (if any)

**Comment by Sahil-Sinha-11** [comment]
Hey @BabyElias @MisRob  I would like to work on this issue. Please assign me this issue.

**Comment by MisRob** [comment]
Hi @Sahil-Sinha-11, thank you for volunteering. I will assign you. Please take some time to understand the current `KTable` and this issue. You're welcome to ask questions here. Note that I will be out of office till the end of October so please mention @BabyElias or @AlexVelezLl during that period of time.

**Comment by Sahil-Sinha-11** [comment]
https://github.com/user-attachments/assets/718d1dff-80bf-4c48-9428-69a707611e63
Hey @AlexVelezLl  I added the unsorted order and it works like this , is it fine? Also How to implement the unit test part?

**Comment by MisRob** [comment]
I don't see the new sorting flow as described in the issue in the video, @Sahil-Sinha-11 as you don't click the sort buttons there.

Regarding unit test, please familiarize yourself with the existing testing suite and use it as a guide.

**Comment by MisRob** [comment]
> I don't see the new sorting flow as described in the issue in the video, @Sahil-Sinha-11 as you don't click the sort buttons there.

I'm sorry @Sahil-Sinha-11, this was just a technical issue on my side - for some reason I saw time elapsing but nothing happening in the video. I tried to preview it again and it works now. Yes, this is expected behavior, thank you.

Here's the reference to unit tests https://github.com/learningequality/kolibri-design-system/tree/develop/lib/KTable/useSorting/__tests__, even though you may also consider starting a new spec file for `KTable` itself and test exactly what you show in video - clicking on the sort buttons.

**Comment by MisRob** [comment]
@Sahil-Sinha-11 If that helps, you can find many more tests in other components, such as here https://github.com/learningequality/kolibri-design-system/tree/develop/lib/tabs/__tests__, to serve as inspiration. We use Vue 2 + Jest + Vue Test Utils. Let us know if you had more questions.

**Comment by MisRob** [comment]
@Sahil-Sinha-11 If that helps, you can find many more tests in other components, such as [https://github.com/learningequality/kolibri-design-system/tree/develop/lib/tabs/__tests__](https://github.com/learningequality/kolibri-design-system/tree/develop/lib/tabs/__tests__), to serve as inspiration. We use Vue 2 + Jest + Vue Test Utils. Let us know if you had more questions.

**Comment by Sahil-Sinha-11** [comment]
> I'm sorry [@Sahil-Sinha-11](https://github.com/Sahil-Sinha-11), this was just a technical issue on my side - for some reason I saw time elapsing but nothing happening in the video. I tried to preview it again and it works now. Yes, this is expected behavior, thank you.

Its fine and thanks for the guidance.

**Comment by Sahil-Sinha-11** [comment]
![Image](https://github.com/user-attachments/assets/f21b84ae-e38a-42ed-9b5f-67ccbb3449b3)
Hey @AlexVelezLl  I added Test for the age section, sorting it back to default value, is this the right way?

**Comment by BabyElias** [comment]
@Sahil-Sinha-11 Yes, this is the right way to test the change introduced. Did you run the `yarn run test` command to see that all checks are passing?

**Comment by Sahil-Sinha-11** [comment]
![Image](https://github.com/user-attachments/assets/c7dcfdef-c830-46d7-aeae-f1ef33cc492f)
@BabyElias It show this ... what should I do?

**Comment by bjester** [comment]
@Sahil-Sinha-11 You might try running the tests with the Jest CLI option `--runInBand`, as [it might shed more light](https://jest-archive-august-2023.netlify.app/docs/27.x/cli#--runinband) on the errors. 

You should be able to do so with `yarn run test --runInBand`

**Comment by Sahil-Sinha-11** [comment]
@BabyElias The error encountered is not in the file I made changes in I made changes in[i.e. i made changes in Ktable but the test fails for kTabLists] should I proceed with a PR?

**Comment by BabyElias** [comment]
@Sahil-Sinha-11 You can go ahead and raise the PR. 
As for the failed test, I believe it's not even a component issue. I hope you are working based on the `develop`  branch and have taken a recent pull for the file changes there. In the case, this can be a memory management/configuration issue within your own system, since the error indicates that the Jest suite could not complete execution, and that's leading to the failed test.
We'll look at it again if the issue persists in the raised PR tests. Thanks!

**Comment by Sahil-Sinha-11** [comment]
@BabyElias  I raised a PR #803 .

**Comment by AlexVelezLl** [comment]
Closed by #803
