### ISSUE TITLE
copying token text adds  "link to section"

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-design-system#8]
For example, copying `tokens.correct` below results in `tokens.correctlink to section`

![image](https://user-images.githubusercontent.com/2367265/76270992-5d381780-6234-11ea-8d6e-a2c2c1f6788c.png)

**Comment by nucleogenesis** [comment]
@indirectlylit I'm not seeing this on production - perhaps it was an artifact of local development tooling or something?

**Comment by indirectlylit** [comment]
it actually depends on whether the selection includes the anchor link or not:

![2020-08-03 19 04 26](https://user-images.githubusercontent.com/2367265/89244842-5ed7f280-d5bc-11ea-8277-53521b6bc071.gif)
