### ISSUE TITLE
KButton, KExternalLink, KRouterLink should look identical with identical inputs

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri-design-system#82]
I think that, perhaps, the only difference between them ought to really just be how we handle events.

- KRouterLink takes a `:to` route which must be a valid router route.
- KExternalLink takes a `download` prop (among others) to manage external URL links
- KButton goes "click" if you click it and you can do what you want with that information.

All of them should have:

- Primary or no?
- Appearance `basic-link` `raised-button` `flat-button`
- `icon` and `iconAfter` props & slots w/ a consistent sizing/styling
- `disabled` prop

And I'm suggesting that If any of the components receive the same values for these props, they should look 100% identical. The only difference being how they act.

**Comment by indirectlylit** [comment]
yes please

**Comment by sairina** [comment]
Closing this issue, as it is continued in #166
