### ISSUE TITLE
Add `radiogroup` role to the `KRadioButtonGroup`

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri-design-system#828]
🌱 **Are you new to the codebase? Welcome! Please see [the contributing guidelines](https://github.com/learningequality/kolibri-design-system/blob/develop/CONTRIBUTING.md).**

## Desired behavior

Add `radiogroup` role to the `KRadioButtonGroup` component as described in https://www.w3.org/WAI/ARIA/apg/patterns/radio/

![Image](https://github.com/user-attachments/assets/1e9b7e1b-0ede-42ac-8797-bdb14a23285c)

## The Value Add

@radinamatic:

>  This role offers a better UX to screen reader users by providing context that they are navigating through (and selecting from) a group of related set of options, and how many they have available.

## References

- https://github.com/learningequality/kolibri/pull/12751#issuecomment-2477835851

**Comment by iamshobhraj** [comment]
@MisRob I'll be happy to take up this task.

**Comment by MisRob** [comment]
Thanks @iamshobhraj, assigned!

**Comment by iamshobhraj** [comment]
@MisRob i opened a pr #846 for this issue. waiting for the reveiw.

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri-design-system/pull/846
