### ISSUE TITLE
Add option to KButtonGroup to prevent wrapping white space + layout shifting

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri-design-system#84]
To fix a problem where two buttons in a Button Group would wrap if their container got too narrow, I added a `white-space: nowrap` rule.

https://github.com/learningequality/kolibri/pull/7393/files#diff-127f6559e90cdff95ed013563555933d

I think this will be a pretty common usage where we want buttons to stay in a side-by-side layout, so it would be helpful if this was either a default or can be controlled via a prop.

**Comment by indirectlylit** [comment]
some related usage scenarios: https://github.com/learningequality/kolibri/issues/7337
