### ISSUE TITLE
KRouterLink - Add `replace` prop

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri-design-system#85]
`<router-link>` is like `router.push()` - in that it creates a new history 

We can extend the `replace` prop from `<router-link>` to `KRouterLink` so that we have the option.

https://router.vuejs.org/api/#replace

I noticed this while looking into the first listed issue in this: https://github.com/learningequality/kolibri/issues/7366

Where the back button "doesn't work" but it's really just that you're getting a bunch of history items pushed to the history stack.

**Comment by sairina** [comment]
@indirectlylit So ideally, we'd want to be able to do something like this?

`<KRouterLink
      :text="facility.name"
      :to="coachClassListPageLink(facility)"
      replace
  />`

**Comment by nucleogenesis** [comment]
Yep and `KRouterLink` should pass the value of that new boolean prop (default: false) to the `<router-link>` in its template.

**Comment by sairina** [comment]
With this as our code: `<KRouterLink  :text="facility.name"   :to="facilityLink(facility)"  replace />`

The way I currently have it, the prop is in the `<router-link>` in the template.

Is this how we want it to come through? 

This is what the Vue devtools shows for `KRouterLink`, and then nested within it, `router-link`:
|`KRouterLink`|`router-link`|
|--|--|
|![Screen Shot 2021-02-09 at 9 55 57 PM](https://user-images.githubusercontent.com/13563002/107471200-9900ee80-6b21-11eb-9a64-d227630277fd.png)|![Screen Shot 2021-02-09 at 9 52 42 PM](https://user-images.githubusercontent.com/13563002/107470973-26900e80-6b21-11eb-98f1-c7bd7e30dd33.png)|
