### ISSUE TITLE
[KTable]: Improve built-in sorting to handle case-insensitive string sorting

### ISSUE THREAD

**Issue by BabyElias** [learningequality/kolibri-design-system#852]
## Product
Kolibri
## Actual behavior

The uppercase characters are sorted before lowercase characters, leading to inconsistent and unexpected results for users.
![Image](https://github.com/user-attachments/assets/9b45e7c9-395c-49e5-b3dc-03c42153e945)

## Expected behavior

The characters should be sorted in alphabetical order irrespective of their case.

## Steps to reproduce the issue
 Go to Kolibri > Facility > Classes
Try adding Classes with different initial letter cases.
See how they are displayed in table when sorted according to class name.

**Comment by BabyElias** [comment]
@MisRob , Can you please assign this issue to me?

**Comment by MisRob** [comment]
@BabyElias :-)

**Comment by MisRob** [comment]
Hi @BabyElias, I wanted to mention that [Learning Equality will be closed from December 23 to January 5](https://github.com/learningequality/kolibri/discussions/12956).

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri-design-system/pull/854
