### ISSUE TITLE
KIconButton - `tooltip` prop became required in a minor release

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri-design-system#86]
@indirectlylit made this prop required in a minor release, which broke existing users.

Let's follow up in a major release in https://github.com/learningequality/kolibri-design-system/issues/168

**Comment by jonboiser** [comment]
Right now, it _is_ required, and causing a lot prop validation errors on Kolibri. Should this be closed?

https://github.com/learningequality/kolibri-design-system/blob/v0.2.x/lib/buttons-and-links/KIconButton.vue#L88-L90

**Comment by indirectlylit** [comment]
I broke this - will look at it tomorrow

ref: https://learningequality.slack.com/archives/CTG8XDTCL/p1616021252011600
