### ISSUE TITLE
KExternalLink ought to open in new tab safely

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri-design-system#94]
We removed the `target="_blank" rel="noopener noreferrer"` due to https://github.com/learningequality/kolibri/issues/7480

However, `KExternalLink` ought to have a boolean prop `openInNewTab` when true will apply the proper attrs.

It also should be tested in Android and other special-build versions of Kolibri designed to run in a web view.

First, this must be finished: https://github.com/learningequality/kolibri/issues/7482 because Kolibri uses `KExternalLink` for internal routing at time of writing.

**Comment by indirectlylit** [comment]
opened a follow-up issue for kolibri: https://github.com/learningequality/kolibri/issues/7712
